### ISSUE TITLE
tooltips in new inline

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#100]
Hi,
Not sure if that is directly related to baton, but it might. For some reason, tooltips (eg. via `<span title="here it goes">blah</span>`) do not display in the "add new inline" form. It works fine if adding a model via its change form, it also displays fine in a saved model inline, but not in the last inline.

FYI, I'm adding an info icon next to fields that have a `help_text` in order to display the help text as a tooltip of the info icon. I tried adding this:
```
    (function($) {
           $('.last-related .info-icon').tooltip();
     })(django.jQuery);
```
at the end of the change_form template, and it does indeed select the icons of this `last-related` elements, but calling `tooltip` raises an error (that `tooltip` is not a function). Looking around on stackoverflow and such, it seems this might be due to a conflict with loaded libraries, but I couldn't figure out if that's the case. 
Do you have any idea of how to trigger the tooltip on these `last-related` elements?

Thanks

**Comment by abidibo** [comment]
Have you tried to use just `jQuery`? Baton exports it globally (attached to the `window` object).

**Comment by etanter** [comment]
Indeed, calling `jQuery('.last-related .info-icon').tooltip()` in the JS console fixes the problem. 

However I don't know how to trigger it at the appropriate time. If I put the code at the end of the `content` block, I guess it runs "too early" because it has no effect. I tried using `$(document).ready(...)` to delay it, but the same happens (loads, but no effect). 
Maybe I should register this on `onReady` event from Baton? How do I do that?
Thanks!

**Comment by abidibo** [comment]
if the new form is created on the fly through, then you can't know when it was inserted in the DOM. Unfortunately, there isn't a proper callback fired at the right moment. I don't think baton onReady will do the job here, indeed Baton itself initializes all tooltips. 
Maybe you'll be forced to use some sort of timeout delay

**Comment by etanter** [comment]
thanks, I'll keep looking for a way to trigger it when appropriate (maybe when the "add another X" button is clicked).

**Comment by etanter** [comment]
I found it, leaving it here if someone faces the same problem:
```
<script>
        django.jQuery(document).on('formset:added', function(event, $row, formsetName) {
        jQuery('.last-related .info-icon').tooltip() });
    </script>
```
based on that: https://docs.djangoproject.com/en/dev/ref/contrib/admin/javascript/#inline-form-events

**Comment by abidibo** [comment]
@etanter ,
great! good to know
