### ISSUE TITLE
Inline change link uses a Font Awesome Pro icon

### ISSUE THREAD

**Issue by avere001** [otto-torino/django-baton#101]
The `.inlinechangelink::before` element shows as an empty box without Font Awesome 5 Pro.

I recommend switching to either the edit icon `\f044` or the alt-pencil icon `\f303`.

![image](https://user-images.githubusercontent.com/5581459/95524604-a9903500-0986-11eb-948e-3664cb99eaf0.png)

**Comment by abidibo** [comment]
Ok thanks,

now using \f304 because already used in other contexts

**Comment by avere001** [comment]
Perfect, thank you
