### ISSUE TITLE
Styling of errors broken for multi-column rows

### ISSUE THREAD

**Issue by avere001** [otto-torino/django-baton#104]
The styling of field errors on the change form is broken for any rows that have multiple columns. See image below.

![image](https://user-images.githubusercontent.com/5581459/96521461-30b29800-1226-11eb-96f5-1ccd66b13748.png)

**Comment by abidibo** [comment]
Ok,
no way I can keep this functionality while keeping the first wrapped field left aligned as the other not wrapped fields.

I'll remove the wrapped fields background and keep them aligned to the left while keeping a box behaviour
