### ISSUE TITLE
Hide GeoDjango bounds fields

### ISSUE THREAD

**Issue by farooqaaa** [otto-torino/django-baton#107]
Is it possible to hide GeoDjango bounds fields?

The bounds field is hidden by default in default Django admin but it's visible in baton:

![image](https://user-images.githubusercontent.com/930117/98053689-f9b1c880-1e5a-11eb-8092-166616d05f54.png)

**Comment by farooqaaa** [comment]
**More details:**

Here's what the field looks like:

`<textarea id="id_fieldname" class="vWKTField required" cols="150" rows="10" name="fieldname"></textarea>`

I have fixed it by adding the following to my CSS:

```
.vWKTField {
    display: none !important;
}
```

**Comment by abidibo** [comment]
I think this is an acceptable solution, I don't get why it's hidden in django admin by default, because the `vWKTField` class is not defined.

**Comment by farooqaaa** [comment]
It's not part of Django's CSS files. They use inline CSS for that. You can check it here:
https://github.com/django/django/blob/6014fd89b3391d72c2e35cb1c6caaed059a51b41/django/contrib/gis/templates/gis/admin/openlayers.html#L7
