### ISSUE TITLE
collapsable stacked inline icon in read-only mode

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#109]
Hi,
When a user has only read permission to a model and its inlines, the blue eye icon (which I assume is normally positioned using the delete button, now missing) is no longer aligned on the right of the inline title, but stuck next to it:
<img width="251" alt="Screen Shot 2020-11-10 at 7 04 10 AM" src="https://user-images.githubusercontent.com/1315554/98659749-3847f700-2323-11eb-889f-dbd061126c71.png">

**Comment by etanter** [comment]
I just tried 1.12.2 and this is still there, and in fact worse now, because when the delete permission is there, the delete box is now stuck to the left as well. It is much better when these icons are stuck to the right, since then the alignment does not depend on the text of each inline.
<img width="637" alt="Screen Shot 2020-11-17 at 12 02 23 PM" src="https://user-images.githubusercontent.com/1315554/99406549-c5172580-28cc-11eb-8456-8db03897f396.png">

**Comment by etanter** [comment]
It used to be:
<img width="690" alt="Screen Shot 2020-11-17 at 12 03 34 PM" src="https://user-images.githubusercontent.com/1315554/99406678-f0017980-28cc-11eb-8d28-627bd9fa6d62.png">

**Comment by abidibo** [comment]
actually is displayed correctly in the demo application, I've given left margin auto to the label. Can you provide a fullscreen screenshot and also a screenshot of the web inspector of the fieldset > h3 please?

**Comment by etanter** [comment]
<img width="961" alt="Screen Shot 2020-11-17 at 12 13 51 PM" src="https://user-images.githubusercontent.com/1315554/99407890-5cc94380-28ce-11eb-8aa6-3319f956148b.png">

<img width="767" alt="Screen Shot 2020-11-17 at 12 13 30 PM" src="https://user-images.githubusercontent.com/1315554/99407852-51761800-28ce-11eb-871e-5082e79429d8.png">

<img width="456" alt="Screen Shot 2020-11-17 at 12 14 46 PM" src="https://user-images.githubusercontent.com/1315554/99408037-87b39780-28ce-11eb-8f6a-9f0575bf8e38.png">

**Comment by abidibo** [comment]
Have you got a custom fieldset template? I can't see the `inline_label` class which is responsible for adding the auto margin on the right

![Screenshot from 2020-11-17 16-36-27](https://user-images.githubusercontent.com/444093/99410699-133f1f80-28f3-11eb-96f1-63614535d7a3.png)

**Comment by etanter** [comment]
yep, that was it! I indeed have custom templates all over, which is a bit fragile...
I added the `inline_label` class and it works. 
Thanks!
