### ISSUE TITLE
how to ensure proper highlighting of selected voice in menu?

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#111]
I have a customized menu with the following:
```
{'label': 'Home', 'type': 'free', 'icon': 'fa fa-home', 'url': 'home/'},
{'label': 'Información', 'type': 'free', 'icon': 'fa fa-address-card', 'url': 'pg/professor/' + str(prof_id) + "/"},
```
when I click on Home, the voice is highlighted as expected:
<img width="227" alt="Screen Shot 2020-11-17 at 12 35 21 PM" src="https://user-images.githubusercontent.com/1315554/99410558-5dafa480-28d1-11eb-8187-6f3f1c000a06.png">

but when I click on Información, the voice isn't highlighted:
<img width="216" alt="Screen Shot 2020-11-17 at 12 35 53 PM" src="https://user-images.githubusercontent.com/1315554/99410604-70c27480-28d1-11eb-85ea-c1cc0a39fbc3.png">
Note that this one points to the change_form of a particular model instance, while the one above is a regular view.

Also, another entry in the menu points to a changelist:
```
 {'label': 'Etudiantes', 'type': 'free', 'icon': 'fa fa-user', 'url': 'pg/student/'},
```
the voice is highlighted properly, but when navigating to one of the elements of the list, the highlighting disappears.

Do you have an idea what's going on and how I could make sure that the voices are properly highlighted?

(in case it matters, this is a custom menu that I set using the `GetAppListJsonView.get_menu` hook)

Thanks!

**Comment by abidibo** [comment]
Well, in case o free voice, the menu voice is highlighted if the location pathname is equal to the voice URL:

```
      let active = false
      if (voice.type === 'free') {
        active = location.pathname === voice.url
      }
```

for other voice types, the check is done with a regular expression, and the voice is considered active if the pathname includes the URL:

```
        if (voice.url) {
          let pathRexp = new RegExp(voice.url)
          active = pathRexp.test(location.pathname)
        }
```

**Comment by etanter** [comment]
that's what i had inferred, and feared, because this is a bit too rigid for my needs... 
Would it be possible to have a way to set an option in the voice to ask the highlight to be "sticky"? meaning, when you click on it, it's highlighted, and will stay so until you click on another one.

Otherwise, the thing I can think of is calling a custom view instead of the change form, but then I don't know how to just call the rendering of the admin form without using a redirect (with a redirect, the problem obviously remains because the url is updated). 

Do you have any clue?

**Comment by etanter** [comment]
I tried using a `model` voice type, and it seems to work fine except for one thing: I don't know how to go a *specific* instance. For instance, the Información voice should open the change_form of the current person (as per a session variable).
Is that already supported? 

If not, could you add an `'args'` attribute for `model` voice, so that it doesn't go to the change list, e.g.:
```
 {'label': 'Información', 'type': 'model', 'icon': 'fa fa-address-card',
  'app': 'pg', 'name': 'professor', 'args': str(prof_id)},
```
(the args attribute could be simply appended to the url)

**Comment by etanter** [comment]
I understand that in the standard scenario where you set the baton menu once and for all in settings.py, it does not make sense to support what I'm asking, but it does make sense related to dynamic menu configuration (#105). Once you do that, then it becomes possible to have voices that point to a specific model instance, as above.

**Comment by etanter** [comment]
@abidibo do you think that's feasible? or is there a better way to do what I'm after? Thanks!

**Comment by abidibo** [comment]
Yes it is, I think about adding a regexp prop to the free voice dict, used to evaluate if the voice should be considered active or not. I'll look into it in the next days, at the moment I'm totally absorbed from deep functional programming studying

**Comment by etanter** [comment]
great, thanks!
good luck with your studying (let me know if there is anything about FP that's not clear - it's my research area ;-))

**Comment by abidibo** [comment]
@etanter ,

I've added a `re` prop for free voices, you can specify a js reg exp used to check for active menu voice. 
The `re` prop is use in js:

```
let re = new RegExp(freevoice.re);
```

**Comment by etanter** [comment]
Hi @abidibo, thanks!
I'm having trouble getting it to work, though. I've been trying many regexps, without success. 
Even the trivial `'re': '/$'` (which should always match given that the location ends with a `/`) does not make the voice active.
Any idea what could be happening here?

**Comment by abidibo** [comment]
I see, it works as children but not as first level voice, I'll fix it now

**Comment by abidibo** [comment]
Fixed in version 1.12.5

**Comment by etanter** [comment]
Indeed, it works as expected now. Thanks!

**Comment by etanter** [comment]
Hi @abidibo,
Now I'm having trouble with the highlighting of children voices. The problem appeared when I move the menu configuration from the static setting to dynamic (as per #105). This means I get the menu object by overriding `get_menu` in my `GetAppListJSonView` subclass (this method looks up the menu def in the current `request.session` store).

Here's what I have in the menu, for which the highlighting doesn't work:
```
{'label': 'Stats', 'type': 'free', 'icon': 'fa fa-signal', 'children': [{'label': 'test1', 'type': 'free', 'url': 'stats/test1/'}, ... ]}
```
I've tried adding an `'re': 'stats/test1/'`, but that doesn't solve the problem. Note that this only happens with free-children. It works fine for app voices, and for top-level free voices as well.

Do you have any idea?

Thanks!
