### ISSUE TITLE
Is there any way i could use tinymce editor ?

### ISSUE THREAD

**Issue by AshishPandagre** [otto-torino/django-baton#113]
I tried using django-tinymce with this, it was successfully integrated. But, it didn't show anything on the HTML field, and appeared something like this. Any help would be appreciated.
![Screenshot (58)](https://user-images.githubusercontent.com/53047854/100517244-41541780-31af-11eb-993a-54b1bcc73a99.png)

**Comment by abidibo** [comment]
@AshishPandagre ,

should be fixed in 1.12.4

If you have overridden the `base_site.html` admin template, make sure to change the Baton init event from `window.onload` to `document.ready`
