### ISSUE TITLE
Field sorting

### ISSUE THREAD

**Issue by dhvcc** [otto-torino/django-baton#120]
Hello, i'm trying to implement custom sorting in admin (to make nulls **always** last)

So the problem here is that sorting takes place **after** `get_queryset` call

Also `get_ordering` returns `()` even if sorting is enabled

This should work in default admin interface, but does not in `django-baton`

**Comment by abidibo** [comment]
Hi @dhvcc ,
that's quite strange since Baton doesn't override any admin view or logic. Are you sure the same works with default Django admin? In such a case can you provide some sample code in order to reproduce the problem?
Thanks
