### ISSUE TITLE
Can't see changelist row attribute

### ISSUE THREAD

**Issue by Jay-Arr-HummingBird** [otto-torino/django-baton#126]
Environment:
Baton 1.13.2, Django version 3.1.4, Python 3.7.6, MAC OSX Big Sur 11.1, Safari 14.0.2

Function:

```
    def baton_cl_rows_attributes(self, request):
        data = {}
        dmu = request.session['Default_multiple_use']
        for p in Poem.objects.filter(poet=request.user).exclude(mu=dmu):
            data[p.id] = {'class': 'table-info',}
        return json.dumps(data)
```

which returns correctly {5: {'class': 'table-info'}}      <<< checked with print statement

The last few lines of my baton/templates/admin/change_list.html are:

```
{% call_model_admin_method model_admin=cl.model_admin method='baton_cl_rows_attributes' as data %}

{% if data %}
    <template data-type="attributes">
        {{ data }}
    </template>
{% endif %}
{% endblock %}
```

**BUT I don't see my change listing records with an attribute table-info blue background change - it looks like this:**

<img width="961" alt="Screenshot 2021-01-02 at 15 14 25" src="https://user-images.githubusercontent.com/56798176/103461006-e2843f80-4d12-11eb-82b5-f1616964d20e.png">

the record **X title** should have the changes attribute.

Can you please offer any help, suggestions or a fix please?

Thank you

**Comment by abidibo** [comment]
Hi @Jay-Arr-HummingBird ,

I can't see anything wrong at a first sight. The default selector is the following:

```
#result_list tr input[name=_selected_action][value=' + key + ']
```

where key is the json key, so the record ID.

Can you check this selector will properly match your element that needs to be highlighted? Maybe you've got some custom templates?

Also, you should see in your DOM something like this (inspect with developer console):

![Screenshot from 2021-01-04 09-40-49](https://user-images.githubusercontent.com/444093/103516538-05c50100-4e71-11eb-98f0-28054b92ff20.png)

**Comment by abidibo** [comment]
Ok, found:

I missed something in the documentation. The function signature should contain the `cl` parameter:

```
 def baton_cl_rows_attributes(self, request, cl):
    # ...  
```

**Comment by Jay-Arr-HummingBird** [comment]
Thank you for your prompt response. 
It now works - all OK.

I think you need to double check that the file 
baton/templates/admin/change_list.html
 has the line:

{% call_model_admin_method model_admin=cl.model_admin method='baton_cl_rows_attributes' cl=cl as data %}

Thanks again.

**Comment by Jay-Arr-HummingBird** [comment]
Arggggh!
I've just noticed another problem. with this.
My original problem was with ther change listing from my POEM model in which I had the 
def baton_cl_rows_attributes(self, request, cl):  function declared
This is the ONLY use of the function in my application.
However when I attempt to list other models (e.g. Competitions) I see the error message:
**** call_model_admin_method error:  'CompetitionAdmin' object has no attribute 'baton_cl_rows_attributes'
And I get similar messages whatever model I attempt to list.

My baton/templates/admin/change_list.html is now
`{% extends 'admin/change_list.html' %}
{% load baton_tags %}
{% block content %}{{ block.super }}

{% for template, position in cl.model_admin.baton_cl_includes %}
    <template data-type="include" data-position="{{ position }}">
        <div class="baton-cl-include baton-cl-include-{{ position }}">
            {% include template %}
        </div>
    </template>
{% endfor %}

{% for template, position in cl.model_admin.baton_cl_filters_includes %}
    <template data-type="filters-include" data-position="{{ position }}">
        {% include template %}
    </template>
{% endfor %}

{% call_model_admin_method model_admin=cl.model_admin method='baton_cl_rows_attributes' cl=cl as data %}

{% if data %}
    <template data-type="attributes">
        {{ data }}
    </template>
{% endif %}
{% endblock %}
`

and my file  baton/templatetags/baton_tags.py
looks like this:

`from google.auth.transport.requests import Request
from django.urls import reverse
from django import template
from django.utils.html import escapejs
from django.core.exceptions import ImproperlyConfigured
from google.oauth2 import service_account

from ..config import get_config

register = template.Library()


@register.simple_tag
def baton_config():
    conf = {
        "api": {
            "app_list": reverse('baton-app-list-json'),
            "gravatar": reverse('baton-gravatar-json'),
        },
        "confirmUnsavedChanges": get_config('CONFIRM_UNSAVED_CHANGES'),
        "showMultipartUploading": get_config('SHOW_MULTIPART_UPLOADING'),
        "enableImagesPreview": get_config('ENABLE_IMAGES_PREVIEW'),
        "changelistFiltersInModal": get_config('CHANGELIST_FILTERS_IN_MODAL'),
        "changelistFiltersAlwaysOpen": get_config('CHANGELIST_FILTERS_ALWAYS_OPEN'),
        "changelistFiltersForm": get_config('CHANGELIST_FILTERS_FORM'),
        "collapsableUserArea": get_config('COLLAPSABLE_USER_AREA'),
        "menuAlwaysCollapsed": get_config('MENU_ALWAYS_COLLAPSED'),
        "menuTitle": escapejs(get_config('MENU_TITLE')),
        "gravatarDefaultImg": get_config('GRAVATAR_DEFAULT_IMG'),
        "loginSplash": get_config('LOGIN_SPLASH'),
    }

    return conf


@register.simple_tag
def baton_config_value(key):
    return get_config(key)


@register.inclusion_tag('baton/analytics.html', takes_context=True)
def analytics(context, next=None):

    analytics_settings = get_config('ANALYTICS')

    if not analytics_settings['CREDENTIALS']:
        raise ImproperlyConfigured(
            'Analytics service account json path missing')  # noqa

    if not analytics_settings['VIEW_ID']:
        raise ImproperlyConfigured('Analytics view id missing')

    # The scope for the OAuth2 request.
    SCOPES = [
        'https://www.googleapis.com/auth/analytics.readonly',
    ]
    # The location of the key file with the key data.
    SERVICE_ACCOUNT_FILE = analytics_settings['CREDENTIALS']

    _credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        scopes=SCOPES, )
    _credentials.refresh(Request())

    # Construct a credentials objects from the key data and OAuth2 scope.
    # _credentials = SignedJwtAssertionCredentials(
    #     _key_data['client_email'], _key_data['private_key'], SCOPE)

    return {
        'token': _credentials.token,
        'view_id': analytics_settings['VIEW_ID']
    }


@register.inclusion_tag('baton/footer.html', takes_context=True)
def footer(context):
    user = context['user']
    return {
        'user': user,
        'support_href': get_config('SUPPORT_HREF'),
        'site_title': get_config('SITE_TITLE'),
        'copyright': get_config('COPYRIGHT'),
        'powered_by': get_config('POWERED_BY'),
    }


@register.simple_tag(takes_context=True)
def call_model_admin_method(context, **kwargs):
    try:
        model_admin = kwargs.pop('model_admin')
        method = kwargs.pop('method')
        return getattr(model_admin, method)(context['request'], **kwargs)
    except Exception as e:
        print('**** call_model_admin_method error: ',e)
        return None

`

**Comment by Jay-Arr-HummingBird** [comment]
Sorry for some unexplained reason 
the code listings (I used the <>)  in the last message has omitted the ** from all the 
kwargs
& print( call_model_admin

**Comment by Jay-Arr-HummingBird** [comment]
FYI: 
when I do a change listing of my POEMS the X title line (the one with record id=5 & the blue background)  has the following  html line generated:

`<tr><td class="action-checkbox"><input type="checkbox" name="_selected_action" value="5" class="action-select"></td><th class="field-title"><a href="/admin/collection/poem/5/change/">X title</a></th><td class="field-dtlu nowrap">2020-Nov-27</td><td class="field-nE2C">2</td><td class="field-nS2M">0</td><td class="field-niP">0</td><td class="field-nR">1</td><td class="field-wip">No</td><td class="field-tag_list">thisisBtag, xxxx</td></tr>

and also this:

`    <template data-type="attributes">
        {&quot;5&quot;: {&quot;class&quot;: &quot;table-info&quot;}}
    </template>

`

**Comment by abidibo** [comment]
@Jay-Arr-HummingBird ,
please try to properly use the snippet and other formatting tools, because I really can't understand what's going on
