### ISSUE TITLE
Suggested environment for compiling JS and scss files for GUI Customization ? 

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#127]
I am having difficulties when compiling Baton customization files in Windows environment. Failed to run commands in the documantation. Espacially  npm run compile gives me so much weird error messages. 

 What is the suggested OS and environment?

For example: 
![npm run compile](https://user-images.githubusercontent.com/1778756/103906236-b3097480-5110-11eb-8a3d-ac77ed34649a.png)
?

**Comment by abidibo** [comment]
Hi @AliPolat ,
I've never tried to compile it on windows system. Maybe there is more information in the log file, from the screen it's impossible to understand what's going on.

Suggested OS is any Linux distro (I use Ubuntu to compile it).

**Comment by AliPolat** [comment]
Thank you..
