### ISSUE TITLE
Updates and improvements

### ISSUE THREAD

**Issue by dhvcc** [otto-torino/django-baton#129]
I've been using `baton` for quite a while now and I want to implement some improvements

1. The main font does not support **cyrillic**. My suggestion is [Blogger](https://www.fontsquirrel.com/fonts/blogger-sans)
`Dosis` (Cyrillic is rendered in DejaVu)
![image](https://user-images.githubusercontent.com/18076967/105696275-246c6400-5f14-11eb-8385-a5a738d9bdf4.png)
`Blogger`
![image](https://user-images.githubusercontent.com/18076967/105696372-46fe7d00-5f14-11eb-831d-116846d0f04c.png)
2. There is no margin on inline headers 
![image](https://user-images.githubusercontent.com/18076967/105688563-cf782000-5f0a-11eb-8652-319a888f484c.png)
I suggest adding a `1rem` bottom margin for a header
![image](https://user-images.githubusercontent.com/18076967/105688679-f0d90c00-5f0a-11eb-88f3-b70b7d10e552.png)
3. No padding for history page default message
![image](https://user-images.githubusercontent.com/18076967/105688768-09e1bd00-5f0b-11eb-95d8-e85c2be1ab7b.png)

That's all i've got

Any comments on how should it be implemented? Like should we override default inline styles or insert custom for `django-baton`

**Comment by abidibo** [comment]
Hi @dhvcc ,

I'm not sure I'll change the Dosis font, I like it so much. Is still possible to change Baton font without too much effort, see https://github.com/otto-torino/django-baton/issues/45. Basically overriding the `admin/base_site.html` template and adding a style block.

Issues 2 and 3 were already addressed in the new v2 branch (based on bootstrap 5), you can try it, it is super stable already, and I think I'll merge it very soon.
