### ISSUE TITLE
voice children highlighting in dynamic menu

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#135]
Hi @abidibo,

A follow-up on #111. Now I'm having trouble with the highlighting of children free voices. The problem appeared when I move the menu configuration from the static setting to dynamic (as per #105). This means I get the menu object by overriding `get_menu` in my `GetAppListJSonView` subclass (this method looks up the menu def in the current `request.session` store).

Here's what I have in the menu, for which the highlighting doesn't work:
```
{'label': 'Stats', 'type': 'free', 'icon': 'fa fa-signal', 'children': [{'label': 'test1', 'type': 'free', 'url': 'stats/test1/'}, ... ]}
```
I've tried adding an `'re': 'stats/test1/'`, but that doesn't solve the problem. Note that this only happens with free children. It works fine for app voices, and for top-level free voices as well.

Do you have any idea?

Thanks!

**Comment by abidibo** [comment]
Moving to dynamic setting shouldn't make any difference as long as you return the same dict.
I've tried to add the same scenario in my demo app, and in my case it works as expected with the `re` addition, I'm testing on branch v2.

**Comment by etanter** [comment]
thanks for confirming that it ought to be working! I insisted and realized that the problem was one of browsing caching, which my `re` addition going unnoticed... sorry about the noise!
