### ISSUE TITLE
Filter icon placement issue  when add permission disabled.

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#136]
Here is the screenshot:

![filter icon misposition](https://user-images.githubusercontent.com/1778756/108592249-06ace600-737e-11eb-9c27-f26fdfdec8c5.jpg)

Django2.2
Python 3.7
Django-baton 2

**Comment by abidibo** [comment]
Thanks @AliPolat ,
fixed in django-baton==2.0.1
