### ISSUE TITLE
Misleading Tab order after an error is thrown in detail page

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#137]
Hi,

When there is an error in a field in detail form, First Tab is activated despite the errenous field is in Second Tab.

Thank You..

![Tab error1](https://user-images.githubusercontent.com/1778756/108818816-02c1d380-75cb-11eb-82e2-fe03f0d100eb.jpg)

![Tab error2](https://user-images.githubusercontent.com/1778756/108818976-3f8dca80-75cb-11eb-8cd0-789a1d196468.jpg)

Django 2.2
python 3.7
django-baton 2.01

**Comment by abidibo** [comment]
Nice catch, bs5 has changed a bit tabs behaviour. I'm on it.

**Comment by abidibo** [comment]
Added e2e test. Fixed in version 2.1.3
