### ISSUE TITLE
Horizontal Menu

### ISSUE THREAD

**Issue by MathiasKowoll** [otto-torino/django-baton#142]
Is it possible to implement a Horizontal Menu? or there is possibility to change the header via templates?

**Comment by abidibo** [comment]
Hi @MathiasKowoll ,

there is no horizontal menu in Baton. I thought about it in the past, but when we decided to design the new left sidebar I think we discarded the idea. It would be too prone to errors to support both a topbar with a horizontal menu and a sidebar with a vertical one. So even if maybe one day we'll implement it it's not something that will happen very soon. Also, it probably could be a secondary menu displayed only when setting `MENU_ALWAYS_COLLAPSED=False`.

As for the templates, Baton only overrides the `admin/base_site.html` template, so you're free to tweak Django admin templates at your will. Clearly, you have to consider that Baton will move some nodes to make its job, for example, it will move the breadcrumbs on top.

**Comment by MathiasKowoll** [comment]
Thx for your reply

**Comment by MathiasKowoll** [comment]
Thx for your reply
