### ISSUE TITLE
problem with tooltips when going 1.12.6 → 2.1.4

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#145]
Hi @abidibo,

So I finally migrated to 2.1.4, and was thrilled to see everything work fine (just had to do some cosmetic adjustments). But, there is one big "but", which is tooltips.

They started behaving super strange: disappearing, blinking in another random part of the page, not appearing anymore, etc. It's highly unpredictable. I could send you a small video to show the weird behavior, if that's helpful.

Code-wise, all these are inserted with `<span ...some classes... data-toggle="tooltip" title="whatever the tooltip says">`, or likewise with `<a href=... data-toggle="tooltip" title="whatever">`

Any idea of what can be going on here? At this stage it's so unusable that my only option would be to deactivate all tooltips (a downgrade for users, since these are helpful at times), or go back to 1.x, which I'd rather avoid in order to keep in the main track of bug fixes and new features.

Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,

can you try to remove the `data-toggle` part?

```
<a href="..." title="whatever">
```

Baton by default activates tooltips on all title attributes. My guess, without inspecting, is that the behaviour is triggered multiple times.

**Comment by etanter** [comment]
it doesn't fix the issue. In fact, some of my tooltips were missing the `data-toggle` part, so my first idea was that this was the issue. Adding/removing that part doesn't change the problem.

**Comment by etanter** [comment]
wait, removing the `data-toggle` part as well as a `info-icon` class I was using seems to be fixing the problem. I'll keep testing and report here.

**Comment by etanter** [comment]
it seems that the problem was with a pattern I had of wrapping an icon in a span (with the title attribute), instead of just putting the title attribute on the icon itself.

**Comment by etanter** [comment]
ok, so it seems that doing both things (removing `data-toggle` and avoiding this "span-wrapping") solves the problem!
thanks for pointing me in the right direction!

**Comment by abidibo** [comment]
Hei @etanter ,
actually, I also have noticed some weird behaviour with tooltips when stressing them a lot (super speedy hover in and out).
I think some problems were caused by bootstrap itself, I've just released Baton==2.1.5 which comes with the new bootstrap 5.0.0.beta3, and to me, the problem seems solved, everything runs smoothly in my tests.

**Comment by etanter** [comment]
Thanks @abidibo! indeed, this morning I installed django-tinymce to have some nice HTML fields, and I noticed that the tooltips of the text editor were immediately disappearing, and sometimes not showing up at all or getting sticky. I've updated to 2.1.5 and it seems ok now.
