### ISSUE TITLE
JS error on login page

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#146]
Hi @abidibo, 

On the login page, I get this JS error:
![image](https://user-images.githubusercontent.com/1315554/113348930-a52d4f00-930d-11eb-95f8-eb6387cd6879.png)

It doesn't affect functionality, but it's weird. The error message is the actual html response. I've tried to reset my login template to the original, and the error still occurs. 

Any idea?

Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,

have you got a custom login URL? Because the menu script should not be executed in the login/logout and popup pages.
If this is the case you can use the [page detection](https://github.com/otto-torino/django-baton#page-detection) feature to indicate your custom URL is a login page.

**Comment by etanter** [comment]
indeed, that was it! thanks!
