### ISSUE TITLE
dirty state of change form with tinymce

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#148]
Hi @abidibo,

Not sure where the problem lies, but I thought you might have a clue.

Since I installed django-tinymce, I noticed that the change forms always complain of a pending edit (with the JS alert "leave site?"), even though I don't touch the form. Just opening a change form and clicking on some other menu link triggers it.

I inserted JS code to check, and the dirty flag of tinyMCE seems to be handled correctly (ie. not dirty on first load, only turns dirty when I actually edit), which makes me think the problem is not with tinyMCE but "above", in the integration with django admin.

Do you have any idea? (I couldn't find anything related on the django-tinymce git)

Thanks!

**Comment by MathiasKowoll** [comment]
There is an option where you can set alert unsave changes. if you set it to False you will no longer receive that popup

**Comment by etanter** [comment]
Thanks Mathias!
The thing is that I'd like the alert to happen, but only when "real". If I just open a change form with an HTMLField and leave, it shouldn't show up.

**Comment by etanter** [comment]
for the record, adding `"add_unload_trigger": False,` and loading the `autosave` plugin made the trick.
