### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Gman1988** [otto-torino/django-baton#15]
Hi,

when I use:

 pip install django-baton  

still I need to manually copy folders to my project right ?

I am getting this error:

    path('baton/', include('baton.urls')),
    NameError: name 'include' is not defined

Best,
Paweł

**Comment by abidibo** [comment]
Hi @Gman1988 , 
actually no.

You don't need to copy anything, include is a function you must import in your `urls.py`

`from django.urls import path, include`

**Comment by abidibo** [comment]
@Gman1988  Any update on this one?

**Comment by Gman1988** [comment]
Apologize, my bad. Everything is working :)
