### ISSUE TITLE
Form includes with right option issue

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#150]
Form includes with right adjustment doubles the included text.

![form_includes-with-riight-option](https://user-images.githubusercontent.com/1778756/114559242-325c9600-9c74-11eb-8dc3-e5a3786be034.jpg)

django 2.2
baton 2.1.3

**Comment by abidibo** [comment]
Hi @AliPolat ,

can you please paste the `ModelAdmin` and the include template?

Thanks

**Comment by AliPolat** [comment]
template:
<!DOCTYPE html>
<html>
    <body> 
        {% if original.patient.birth_date is not None %}
            {{original.patient.birth_date}}
        {% endif %}
    </body>
</html>


and part of Model Admin:

    fieldsets = (
        ('Request', {
            'fields': ('requester_type', 'requester', 'contact', 'patient', 'get_birth_date', 'requester_work_order', 
                       'detail', 'request_date', 'objection_date_exemption', #'type', 
                       'priority', 'request_via', 'abnormal_request', 'subpoena', #'invoice_sent', 'invoice_paid', 
                       'invoice_status', 'page_count', 'comment', #('received_date', 'completed_date'), 
                       ('user', 'created_at', 'updated_at', 'id')),
            'classes': ('baton-tabs-init', 'baton-tab-group-status--inline-assignment--inline-status--inline-followup--inline-document',),
            'description': 'Request information'
        }),
       ('Assignments / Status / Follow ups / Documents', {
            'fields': (('get_detail', 'get_request_via'),), #'fields': (('get_detail', 'get_type', 'get_request_via'),),
            'classes': ('tab-status', ),
            'description': 'Add or change request status and documents'

        }),
    )

    preserve_filters = False
    list_per_page = 25
    radio_fields = {"requester_type": admin.HORIZONTAL, 'priority': admin.HORIZONTAL, 'request_via': admin.HORIZONTAL,} # "invoice_status": admin.HORIZONTAL, 
    #autocomplete_fields = ['patient',] 
    #raw_id_fields = ['requester']
    list_select_related = True 
    show_full_result_count = False

    list_filter = [#('requester', admin.RelatedOnlyFieldListFilter),
                   RequesterFilter,
                   'priority',
                   'detail', 
                   'request_via',
                   'abnormal_request',
                   'subpoena',
                   ('assignment__assigned_to',  admin.RelatedOnlyFieldListFilter), 
                   'last_status', 
                   'last_status_date',
                   ('user',  admin.RelatedOnlyFieldListFilter), 
                   'invoice_status']  

    search_fields = ['id', 'requester__name', 'priority', 'requester_work_order', 'user__username',  'status__name', 
                     'assignment__assigned_to__username', 'patient__first_name', 'patient__last_name', 'patient__birth_date']

    ordering = ('-id',)
    date_hierarchy = 'created_at'

    inlines = (AssignmentInline, StatusInline, FollowupInline, DocumentInline)

    baton_form_includes = [
        ('app/patient_birth_date.html', 'patient', 'right', )
    ]

**Comment by AliPolat** [comment]
template : 
----------

<!DOCTYPE html>
<html>
    <body> 
        {% if original.patient.birth_date is not None %}
            {{original.patient.birth_date}}
        {% endif %}
    </body>
</html>

**Comment by AliPolat** [comment]
part of ModelAdmin : 
-----------------------

    fieldsets = (
        ('Request', {
            'fields': ('requester_type', 'requester', 'contact', 'patient', 'get_birth_date', 'requester_work_order', 
                       'detail', 'request_date', 'objection_date_exemption', #'type', 
                       'priority', 'request_via', 'abnormal_request', 'subpoena', #'invoice_sent', 'invoice_paid', 
                       'invoice_status', 'page_count', 'comment', #('received_date', 'completed_date'), 
                       ('user', 'created_at', 'updated_at', 'id')),
            'classes': ('baton-tabs-init', 'baton-tab-group-status--inline-assignment--inline-status--inline-followup--inline-document',),
            'description': 'Request information'
        }),
       ('Assignments / Status / Follow ups / Documents', {
            'fields': (('get_detail', 'get_request_via'),), #'fields': (('get_detail', 'get_type', 'get_request_via'),),
            'classes': ('tab-status', ),
            'description': 'Add or change request status and documents'

        }),
    )

    preserve_filters = False
    list_per_page = 25
    radio_fields = {"requester_type": admin.HORIZONTAL, 'priority': admin.HORIZONTAL, 'request_via': admin.HORIZONTAL,} # "invoice_status": admin.HORIZONTAL, 
    #autocomplete_fields = ['patient',] 
    #raw_id_fields = ['requester']
    list_select_related = True 
    show_full_result_count = False

    list_filter = [#('requester', admin.RelatedOnlyFieldListFilter),
                   RequesterFilter,
                   'priority',
                   'detail', 
                   'request_via',
                   'abnormal_request',
                   'subpoena',
                   ('assignment__assigned_to',  admin.RelatedOnlyFieldListFilter), 
                   'last_status', 
                   'last_status_date',
                   ('user',  admin.RelatedOnlyFieldListFilter), 
                   'invoice_status']  

    search_fields = ['id', 'requester__name', 'priority', 'requester_work_order', 'user__username',  'status__name', 
                     'assignment__assigned_to__username', 'patient__first_name', 'patient__last_name', 'patient__birth_date']

    ordering = ('-id',)
    date_hierarchy = 'created_at'

    inlines = (AssignmentInline, StatusInline, FollowupInline, DocumentInline)

    baton_form_includes = [
        ('app/patient_birth_date.html', 'patient', 'right', )
    ]

**Comment by abidibo** [comment]
@AliPolat ,

the only way I could find to replicate it is to add the include two times in the `ModelAdmin`, like this:

``` python
    baton_form_includes = [
        ('news/admin_datetime_include.html', 'datetime', 'top', ),
        ('news/admin_content_include.html', 'content', 'above', ),
        ('news/admin_title_include.html', 'title', 'right', ),
        ('news/admin_title_include.html', 'title', 'right', ),
    ]
```

Otherwise all works as expected and I cannot reproduce it. Can you confirm you are not doing something similar?

**Comment by AliPolat** [comment]
Yes I confirm that I include once. Even simple text in html doc doubles. Other options work correctly.

**Comment by abidibo** [comment]
Ok, can you confirm it happens also with other fields and not only with the `patient` one?

Also, it's not necessary at all to wrap everything in a complete HTML document with DOCTYPE HTML etc... Because that template is included as is inside the dom, so just put what you need:

``` HTML
        {% if original.patient.birth_date is not None %}
            {{original.patient.birth_date}}
        {% endif %}
```

**Comment by AliPolat** [comment]
Thank you. I corrected it now. But even simple text in HTML doc is multiplied by 2

**Comment by abidibo** [comment]
Ok, can you confirm it happens also with other fields and not only with the patient one?

**Comment by AliPolat** [comment]
Patient is a foreign key. I changed to a text field to include the birth_date  it has worked now.

**Comment by AliPolat** [comment]
Other foreign key fields on the same Admin page cause the same issue. Other nonrelational fields work as expected.

**Comment by abidibo** [comment]
that's weird, I cannot reproduce it, can you check with the inspector if you have multiple `template` tags with the same id? In your case `template-patient`

![Screenshot from 2021-04-13 16-36-28](https://user-images.githubusercontent.com/444093/114570918-84062000-9c76-11eb-8914-e4761a22c7f9.png)

**Comment by AliPolat** [comment]
I removed the django-easy-select2.  Now it works. I am very sorry.  Maybe this thread helps someone with the same problem.

**Comment by abidibo** [comment]
Glad you solved it, don't worry. Have a nice day!

**Comment by AliPolat** [comment]
Thank you so much
