### ISSUE TITLE
beginning GUI issues 

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#16]
Hi,
I'm trying to evaluate migrating from django-suit to django-baton, for an app running on Django 1.11. I like the minimalist philosophy and the general design, cool stuff!

After applying the basic install instructions, and removing all django-suits files around, everything seems fairly functional except that:
- the menu does not show up at all (it blinks on page load then disappears and I can't find a way to get it back (also in the blink it appears to be empty, despite my config)
- the horizontal banner (with support, copyright, etc.) shows up on the bottom of the page when first loaded, but it does not move as I scoll down the page, so it obfuscates the middle of the info.

See snapshot attached where both issues can be appreciated.
<img width="511" alt="Screen Shot 2019-04-26 at 10 44 00 AM" src="https://user-images.githubusercontent.com/1315554/56815888-5f59d900-6810-11e9-99cc-1906b36a8459.png">

Any help is greatly appreciated!

Thanks

Éric

**Comment by abidibo** [comment]
Hi @etanter ,
I've just tried the last baton version 1.4.0 with a django 1.11.1 project and all works as expected.

The first thing to check if migrating from other admin apps to baton is whether or not admin templates, css or js are overwritten from other apps. Particularly admin templates, since baton relies on the base django html structure to inject stuff. Also some more info can help us to find the actual problem:

- browser version and os
- browser console errors/warnings, if any

**Comment by etanter** [comment]
Thanks @abidibo for the quick response.
I've removed all admin templates and so on, but same problems.

I'm using Chrome (version 73) on mac os. I'm running on incognito mode to make sure cache does not interfere.
When I open the JavaScript console in Chrome, there is indeed an error reported in Menu.js:

![image](https://user-images.githubusercontent.com/1315554/56826976-8540a700-682b-11e9-8729-50dd7006e94e.png)

Any clue?

**Comment by abidibo** [comment]
This is so weird! You shouldn't see the Menu.js because it is included in the baton bundle by webpack, and also, Menu.js is clearly a js file, while in the console it is printing the base_site template...

Is this the whole trace of the js error? Have you tried to customize baton recompiling it, or you've just installed it from pip and used it as is?

**Comment by etanter** [comment]
yep, it's the whole trace. I haven't done any customization, just ran pip install (in a virtual env).

**Comment by etanter** [comment]
well, it was a screenshot, so trimmed at the end. I attach the full trace as a txt file.

[127.0.0.1-1556320551635.txt](https://github.com/otto-torino/django-baton/files/3123237/127.0.0.1-1556320551635.txt)

**Comment by abidibo** [comment]
I woluld check if the ajax request that baton performs to retrieve the menu data fails fore some reason, or returns the wrong response.

Please, recharge the page looking at the newtwork tab of the developer console, and search for the `app-list-json` request. You should see something like the attached screenshot. If you see something else, like the whole admin index template, then it should be some misconfiguration in the urls part, like the baton urls are "overwritten", or some error occurs

![Screenshot from 2019-04-27 08-54-25](https://user-images.githubusercontent.com/444093/56846036-24b47700-68ca-11e9-839b-0ff9dd18cda7.png)

**Comment by etanter** [comment]
in the response it says "failed to load response data"
no super informative, I'm afraid

**Comment by etanter** [comment]
fyi I'm using a trimmed-down BATON config from the docs:
````
BATON = {
    'SITE_HEADER': 'Baton',
    'SITE_TITLE': 'Baton',
    'INDEX_TITLE': 'Site administration',
    'SUPPORT_HREF': 'https://github.com/otto-torino/django-baton/issues',
    'COPYRIGHT': 'copyright © 2017 <a href="https://www.otto.to.it">Otto srl</a>', # noqa
    'POWERED_BY': '<a href="https://www.otto.to.it">Otto srl</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'MENU': (
        { 'type': 'free', 'label': 'Custom Link', 'url': 'http://www.google.it', 'perms': ('flatpages.add_flatpage', 'auth.change_user') },
    ),
}
````

**Comment by abidibo** [comment]
So:

1 - what do you see if (when logged in) you open a browser tab with this url http://localhost:8000/baton/app-list-json/
2- Post here your main urls.py

**Comment by etanter** [comment]
ok, got it, it was a bug in my main urls (my admin pages have a configurable suffix (eg. ".../dev/admin/...") and I hadn't configured the baton urls accordingly (needed to have `url(r'^' + URL_SUFFIX + 'baton/', include('baton.urls')),`)

thanks for your help tracking down this issue!!
