### ISSUE TITLE
Integration with django-import-export

### ISSUE THREAD

**Issue by Abe-2** [otto-torino/django-baton#161]
It seems like django-import-export is not displayed correctly due to mismatch with the CSS classes where import-export uses django's default. Any idea on how to fix this?

**Comment by MathiasKowoll** [comment]
I have the same issue, I think we need to overwrite de Django-import-export html

**Comment by abidibo** [comment]
I'll look into it soon

**Comment by abidibo** [comment]
@Abe-2 , @MathiasKowoll should be fixed in develop branch, could you try it please?

**Comment by MathiasKowoll** [comment]
@abidibo I tried to pip install from git without success

**Comment by abidibo** [comment]
I'll take a look at the beginning of next week

**Comment by abidibo** [comment]
```
pip install https://github.com/otto-torino/django-baton/archive/develop.zip
```

I see this:

![Screenshot from 2021-05-31 09-38-21](https://user-images.githubusercontent.com/444093/120158085-067d7b80-c1f4-11eb-8648-a69693f81c59.png)

**Comment by MathiasKowoll** [comment]
@abidibo 
<img width="726" alt="Screen Shot 2021-05-31 at 08 44 12" src="https://user-images.githubusercontent.com/15032652/120195147-6a03ab00-c1ec-11eb-9a86-90f1d8744e85.png">

refreshed and reinstall looks like your comment button all my forms are messed up

**Comment by abidibo** [comment]
Yes I know, I'm working on it, but what about the export page, does it look ok?

**Comment by MathiasKowoll** [comment]
> Yes I know, I'm working on it, but what about the export page, does it look ok?

It looks ok, thanks for your effort.

**Comment by abidibo** [comment]
@MathiasKowoll 

develop branch should be fine now

**Comment by MathiasKowoll** [comment]
@abidibo forms looks ok, import-export button show ok. dropdown show not ok. but better than before
<img width="1390" alt="Screen Shot 2021-05-31 at 12 39 29" src="https://user-images.githubusercontent.com/15032652/120222001-4bfa7280-c20d-11eb-8d96-36b2eab90c6c.png">

**Comment by abidibo** [comment]
Browser?

This is what I see

![Screenshot from 2021-05-31 18-44-14](https://user-images.githubusercontent.com/444093/120222484-4c603100-c240-11eb-8316-253befc46217.png)

**Comment by MathiasKowoll** [comment]
Safari.

edge chrome and firefox looks ok

**Comment by abidibo** [comment]
Ok, I suppose you see all dropdown the same way, or not?

**Comment by MathiasKowoll** [comment]
This is the only one because I use Django-autocomplete-light for all my dropdowns. Just made a quick test and all default dropdowns without dal looks like the screenshot I took.

**Comment by abidibo** [comment]
Ok, I forgot to add again postcss loader, now should work

**Comment by MathiasKowoll** [comment]
Now It works, great job thanks @abidibo
