### ISSUE TITLE
Baton version attribute

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#168]
for testing/dev purposes it would be very helpful if there were a `Baton.version` attribute so that one could easily check in a console which exact version of baton is loaded.

**Comment by abidibo** [comment]
Added Baton revision
![Screenshot from 2021-06-01 16-56-23](https://user-images.githubusercontent.com/444093/120345160-85f57280-c2fa-11eb-9149-bfa99ee11531.png)

**Comment by etanter** [comment]
Thanks @abidibo
