### ISSUE TITLE
Open last tab after submit

### ISSUE THREAD

**Issue by gual** [otto-torino/django-baton#17]
Is there an option to preserve the last tab after saving an instance?

Lets say I have configured "tab 1", "tab 2", "tab 3": I'm on tab 2 and choose to save my progress, currently after saving I'm redirected to tab 1, I would like to be redirected to tab 2.

If there isn't a built-in function, I would be interested in exploring adding it, which will be the best approach to this?

(Awesome work btw)

**Comment by abidibo** [comment]
Hi @gual ,
baton supports already to open a form tab on document load, just by appending the right hash to the url, as explained at the end of this page:
https://django-baton.readthedocs.io/en/latest/form_tabs.html

So it's quite simple to add such functionality, simply the submitted url when clicking the "submit and continue" button should contain such hash.

I like this enhancement, and I'll definitely add it in the next baton release (if you want to make PR you're welcome). Till then adding this functionality it's as simple as adding this code:

    <script>
        (function ($) {
            $(window).on('load', function () {
                if(Baton.page() === 'change_form') {
                    $('.nav-tabs .nav-link').on('click', function () {
                        location.hash = $(this).attr('href');
                    })
                }
            })
        })(jQuery)
    </script>

In the `admin/base_site.html` template (just make sure to start from the baton one which includes the js app)

Also it would be nice with the same functionality, to add support for a callback which baton eventually calls after being completely loaded (https://github.com/otto-torino/django-baton/blob/master/baton/static/baton/app/src/index.js#L47)

Thanks for your feedback!

**Comment by gual** [comment]
Awesome! The fix is working. Thanks, @abidibo.

The dispatcher looks like an overhaul lol and I would let that job to you :) About the other solutions they look _doable_ for me (with guidance). Let me know what you choose.

**Comment by abidibo** [comment]
Hi @gual,
I've added all the functionality in the develop branch (persistence of selected tab + onReady, onMenuReady, OnNavbarReady signals, documented here https://github.com/otto-torino/django-baton/tree/develop#signals). I'll not release this now, because I think there isn't enough material to justify a 1.5.0, so before merging in master I'd like to add more stuff. Cheers!
