### ISSUE TITLE
Multiple choice list filter

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#170]
Hi everybody,

it would be nice to integrate the multiple choice list filter class (https://github.com/ctxis/django-admin-multiple-choice-list-filter) to the baton list filter class set.

Thank You.

**Comment by abidibo** [comment]
We're considering this, we need to make sure it can play well with the `CHANGELIST_FILTERS_FORM` option

**Comment by abidibo** [comment]
Added to 2.6.0
