### ISSUE TITLE
Allowing user-specified configuration values

### ISSUE THREAD

**Issue by tswicegood** [otto-torino/django-baton#171]
I was working with a personal fork of django-baton and I wanted to turn off Gravatar support. It's easy enough to just remove the JavaScript, but that would be harder to maintain long term than making Gravatar support optional and getting that contributed back upstream. I have a rough working copy that would allow for:

```python
BATON = {
    "GRAVATAR": False,
}
```

In doing this, though, I came across the need to modify `baton.templatetags.baton_tags.baton_config` to add the change. I have an idea for a better way to do this.

---

What do y'all think about adding a `baton.config.get_all_config_as_json` that does something like this:

```python
def get_all_config_as_json():
    json_config = {}
    all_known_keys = set(list(settings.BATON.keys()) + list(default_config.keys()))
    for key in all_known_keys:
        json_key = convert_to_camel_case(key)
        json_config[json_key] = get_config(key)
    return json_config
```

This would simplify `baton_config` as all it would need to do is:

```python
conf = {
    "api": {
        "app_list": reverse('baton-app-list-json'),
        "gravatar": reverse('baton-gravatar-json'),
    },
    **get_all_config_as_json()
}
```

Happy to open up a PR if this is something y'all would be interested in.

**Comment by abidibo** [comment]
I don't know.
I get the point of avoiding somehow repeat all the configuration items. But at the same time, that template tag acts as a whitelist for the properties that are passed to the js Baton instance. And it's also a single point where you can see clearly which variables are passed. It filters out weird stuff being set in the config, as not JSON convertible entities and so on.

Let's see what other people have to say about this.

**Comment by MathiasKowoll** [comment]
I think it is a good Idea so we can get more customization

**Comment by abidibo** [comment]
@MathiasKowoll,
actually, the level of customization remains the same, because you must implement the functionality clientside in the npm app. 
What you get, is to save a line that you need to add in the templatetag.
