### ISSUE TITLE
inline tabs not showing

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#18]
Hi,
I have another issue, which might be related to the general UI bugs I'm encountering, but in case it's not, would be good to know ;-)

I have successfully been able to set up fieldset tabs, but inline tabs do not work.
See screenshot: there is a phantom tab (empty label, see light gray border in place of the "third" tab). The link is correct (see bottom of the picture). Beyond not having a title, it's empty if I click on it, and the corresponding inlines are visible on the main tab, instead of being moved to that tab.

<img width="364" alt="Screen Shot 2019-04-26 at 7 48 52 PM" src="https://user-images.githubusercontent.com/1315554/56841626-ec2a8400-685c-11e9-8740-e567cf0143e9.png">

I have `inlines = [..., GrantInline, ....]`
and then in the fieldsets, the Main one has `'baton-tab-inline-grant'` in the list of classes.

**Comment by abidibo** [comment]
This happens to me when I misspell something in the css class definitions used to activate the tab behaviour. Please post here your complete ModelAdmin class along with the models involved (I want to see the related_name props if any)

**Comment by etanter** [comment]
indeed it was due to related names! sorry for not properly reading the f... manual ;-)

**Comment by etanter** [comment]
(fwiw, it might be good to put an explicit note in the docs to bring the attention on that issue)
