### ISSUE TITLE
Static files are not collected

### ISSUE THREAD

**Issue by martn** [otto-torino/django-baton#181]
Hi all,

I have problems with both master and develop version of Baton and Django 3.2.5

When running collectstatic it fails to overwrite static files:

`Found another file with the destination path 'admin/css/base.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/changelists.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/dashboard.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/forms.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/responsive.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.`

Therefore the admin does not work as expected. The standard django style is loaded.

Any clues?

**Comment by abidibo** [comment]
Hi @martn ,
have you declared baton before django.contrib.admin in your INSTALLED_APPS?

**Comment by martn** [comment]
Hi @abidibo,

oh I haven't. Putting it before django.contrib.admin solved my problem.. 
Thanks a lot!!
Martin
