### ISSUE TITLE
Access, specific custom url

### ISSUE THREAD

**Issue by MathiasKowoll** [otto-torino/django-baton#185]
Hi @abidibo 

Is it possible to access a specific custom url without using free type?

**Comment by abidibo** [comment]
@MathiasKowoll ,

no, at the moment the only way to specify custom URLs is to use a free type

**Comment by MathiasKowoll** [comment]
The problem I'm facing is with django-tenants, as they do now work with subfolder tenants it needs to change the requested url for the tenant and with custom url I can't.

This with model and apps works flawsly 

Hope it can be implemented as this is a good way to create custom tenant base apps.

**Comment by abidibo** [comment]
@MathiasKowoll ,
please write down an example with some code of what you need with an user perspective solution, and we'll see if we can add such functionality (but not before some holidays :))

**Comment by MathiasKowoll** [comment]
@abidibo will write a custom example and will let you know.
I also have another issue with login son maybe you will be able to see this too. 
Will create a full example for this.

**Comment by MathiasKowoll** [comment]
@abidibo, still preparing the repo I didn't have much time but I fix some of my problems using:
Baton.detectPageHook = fn => /login/.test(location.pathname) ? 'login' : fn()

but my javascript and jquery knowledge is very minimal. how can I add  a second condition and then otherwhise like a case for: /logout/.test(location.pathname)

Thx in advance

**Comment by MathiasKowoll** [comment]
Resolved adding 
Baton.detectPageHook = fn => /login/.test(location.pathname) ? 'login' : /logout/.test(location.pathname) ? 'logout' : fn()
to button initialization of button, this way solved my login logout issues not working correctly on Django-Tenants when using subfolder approach

**Comment by abidibo** [comment]
I'm closing this for now, feel free to re-open it when needed

**Comment by MathiasKowoll** [comment]
@abidibo Hi, I manage to use all custom url with the application Django-tenants, will create a new issue for custom url's in settings.

Thx for all the support.
