### ISSUE TITLE
some style lost when linking to a custom page

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#19]
Hi,

In the menu bar I have links to custom pages (basically, stats about the app), implemented via views that render typical templates.
 
In my django-suit implementation, I would just link to the page as if it were external, and these templates start with `{% extends "admin/base_site.html" %}` in order to inherit the style, and then only define a `{% block content %}`.

I tried that with baton, using a `'type': 'free',` entry in the `MENU`, but the problem is that even though it has the `extends` tag, the rendered page has the default site name (ie. `Django administration` instead of whatever is configured in the `BATON` variable). There's also no clickable user menu on the top right corner. The rest of the displayed page is good: menu, style of the content, and footer.

Thanks!

**Comment by abidibo** [comment]
Yes, if you write a custom view you need to fill the template context with the necessary variables, which are not present by default at the moment, in order to show the site title you need to pass `site_header`, and in order to show the user dropdown `has_permission`:

    mycontext = {
        #...
        'site_header': 'My Title',
        'has_permission': True,
    }

**Comment by etanter** [comment]
perfect, thanks!
