### ISSUE TITLE
Custom URL in settings.

### ISSUE THREAD

**Issue by MathiasKowoll** [otto-torino/django-baton#193]
Hi, I thinks that more than a bug it is a feature.

I use case is the following.

I write custom url for some specific usage like payment and therefore I overwrite some methods in the admin.

I define the following

def get_urls(self):
        urls = super().get_urls()
        my_urls = [
            path('my_url/<int:value>/', self.admin_site.admin_view(self.create_sale_process), name='my_url'),
        ]
        return my_urls + urls

the way I can access this url in application is reverse(admin:my_url).

right now I didnt find any way to pass an dynamic url into settings the problem with getting the full URL static in settings is that it cannot be reused.

Any help will be highly appreciated.

**Comment by abidibo** [comment]
I'm not sure I understood the use case here. But the settings are static at the moment. In any case, if what you need is a dynamic menu, as per https://github.com/otto-torino/django-baton/issues/105, you can override the `get_menu` method of the `GetAppListJsonView`, see https://github.com/otto-torino/django-baton/blob/8ae3b2ea1b875cf38031ee4a58a88e9478447193/baton/views.py#L39
