### ISSUE TITLE
Static urls not working with StaticRootS3Boto3Storage

### ISSUE THREAD

**Issue by guglielmo** [otto-torino/django-baton#195]
When using `StaticRootS3Boto3Storage` as `STATIC_STORAGE`, 
the fonts in the static files are not correctly pointed to the aws storage links (a bucket on S3).

The javascript application assumes that the links are in the `/static` directory on the web server, and both javascript and fonts are not loaded correctly. The `baton.min.js` file contains such links.

By modifying the `baton/static/baton/app/webpack.prod.js`, and adding

```
  output: {
    ...common.output,
    publicPath: "https://[BUCKET].s3.eu-central-1.amazonaws.com/static/baton/app/dist/",
  },
```
where [BUCKET] is the actual bucket name,
and re-building the dist files using webpack, the javascript code now references the correct links.

There is still a problem with the fonts which seems to be loaded from the web server (requests go to the /static folder  of the web server, and returns a 404 response).

The interface works correctly, but the icons are missing.

I was able to detect the *wrong* links to the font files inside the `<style/>` section of the html page, but 
could not determine which part of the source files are responsible for the construction of that tag.

I suppose `src/style/*.scss` files are transpiled into the style tag by webpack, but I'm no deep expert in frontend development, so here I am asking for help.

**Comment by guglielmo** [comment]
I've managed to somehow solve this with a backend redirect.

All requests going to `static/` are redirected to the S3 url, (with CORS policies enabled).

**Comment by abidibo** [comment]
Great!

**Comment by Nick-foote** [comment]
@guglielmo How did you implement your fix? I'm in the same situation.

The JS files loads fine, ie `https://[BUCKET_NAME].s3.amazonaws.com/static/baton/app/dist/baton.min.js `,
but not the SVG or font files, and doesn't try to load from the bucket: `http://localhost:8000/static/baton/app/dist/66104b766c3d0462b3c5.woff2`

For redirecting did you implement something like the below:
`www.example.com/static/baton/app/dist/*`
to:
`https://[BUCKET_NAME].s3.eu-central-1.amazonaws.com/static/baton/app/dist/`
