### ISSUE TITLE
Font urls are not STATIC_URL dependent

### ISSUE THREAD

**Issue by Lenni** [otto-torino/django-baton#198]
Even if STATIC_URL is set to e.g. "static_deploy", the template tries to access them them from "static"
![image](https://user-images.githubusercontent.com/6625244/147394103-32df623b-5d9e-4702-a245-494f6e277aca.png)

**Comment by abidibo** [comment]
Hi @Lenni ,
this is a known limitation, at least without recompiling the js app. The fact is that these paths are needed before runtime, when compiling the application, see https://github.com/otto-torino/django-baton/issues/81#issuecomment-661899608

**Comment by Nick-foote** [comment]
@abidibo Could you please explain how/where we would add our own url and what steps/commands we would need to recompile the application (for those of us that aren't Frontend facing)

Thanks 😊

**Comment by abidibo** [comment]
@Nick-foote 
Line 14 of https://github.com/otto-torino/django-baton/blob/master/baton/static/baton/app/webpack.common.js

Change the `publicPath`, i.e.

```
  output: {
    path: path.join(__dirname, "dist"),
    publicPath: "/static-changed/baton/app/dist/",
    filename: "baton.min.js",
    clean: true,
  },
```

Then recompile the app (inside baton/static/baton/app):

```
$ npm run compile
```

Then place the generated bundle in app declared before baton in the `INSTALLED_APPS` As explained here: https://github.com/otto-torino/django-baton#customization
