### ISSUE TITLE
how to group custom links in menu

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#20]
Is there a way to group custom links (ie. `'type': 'free'` in the `MENU` config) under a collapsable menu item, just like it works for a `'type': 'app'` block?

**Comment by abidibo** [comment]
No there's no such functionality at the moment, I'll think about the possibility to add nested voices though.

**Comment by abidibo** [comment]
@etanter ,
the functionality is now available in the develop branch (https://github.com/otto-torino/django-baton/tree/develop#configuration-menu), if you want to try it. It will be released in the v1.5.0 when I'll add more stuff.

**Comment by etanter** [comment]
it works perfectly, thanks a lot!
