### ISSUE TITLE
fixed width font for numbers

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#21]
Hi, while I find the font very elegant, the fact that numbers are not fixed width makes large lists of numbers and dates look disorganized. Is there an option for numbers to be rendered with fixed width?

**Comment by abidibo** [comment]
Hi @etanter ,
actually no, there isn't a simple way to apply a monospaced font only to numbers and dates. Django does not wrap data in elements providing type information (for example with different css classes). 

It's easy to globally change the font family, just add a rule to the body element marking it as !important. While if you need to have different fonts in different sections/divs/tables ans so on you should do that manually inspecting the dom to understand the proper rule to apply.

**Comment by etanter** [comment]
thanks @abidibo!
