### ISSUE TITLE
modals for change forms

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#215]
Hi,

I've seen the new modal feature and I'm hoping to use this as an alternative to popups and extra navigation whenever a user needs to add or edit a "small" model from another one. (For instance, adding a new City when editing a Person, it would be nicer with a modal than with a popup).

Using the `url` attribute (eg. `app/city/1/`) is not helpful because it's the full blown page that gets into the modal (with headers etc.) and that interferes with the current page. 
One would need to point to the "meat" of the change url.  (Adding `?_popup=1` to the url doesn't seem to have any effect.)

What would be the best way to do that?

Thanks!

**Comment by victorpachecolopez** [comment]
Hi, algo sencillo que he implementado:

Agregar en base_site.html

` <script>

        var modalbaton = null;
        var firstPageLoad = 1
        
        function onloadModalIframe() {

            if (iframeModal.contentWindow.document.documentElement.innerHTML.includes('popup' + '_response.js') == true) {
                modalbaton.close();
                location.reload();
            }
        }

        function openModalIframe(url, titulo){
            alto = window.innerHeight*90/100;
            let modalIframe = new Baton.Modal({
                title: `<strong>${titulo}</strong>`,
                content: `
                    <div style="">
                    <iframe id="iframeModal"
                        onload="onloadModalIframe()"
                        src="${url}"
                        width="100%"
                        height="500px">
                    </iframe>
                    </div>
                `,
                size: 'lg',
                hideFooter: true,
            })
            modalbaton = modalIframe;
            modalIframe.open();
            modalIframe.modalObj.on('hidden.bs.modal', function (e) {
                firstPageLoad = 1;
            });

        }

    </script>`

Crea links a las acciones así

`<button type="button" class="btn btn-secondary" onclick="openModalIframe('{% url 'admin:agenda_atencion_add' %}' + '?_popup=1', 'Añadir atención')">
            <i class="fas fa-plus"></i> Añadir atención
        </button>`
   
Call actions from change_list

<a href="https://ibb.co/fnzV9Fm"><img src="https://i.ibb.co/s6dpCRL/Captura-de-pantalla-2023-07-31-10-21-06.png" alt="Captura-de-pantalla-2023-07-31-10-21-06" border="0"></a>

**Comment by etanter** [comment]
Thanks a lot @victorpachecolopez I'll try it out asap and will post feedback!
