### ISSUE TITLE
windows 10 and Django 4.0.4 installation

### ISSUE THREAD

**Issue by c-vision** [otto-torino/django-baton#218]
Hi,
I always get this error

ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'G:\\Sources\\Django\\auth\\dashboards\\Baton\\example\\django4.0.4\\Lib\\site-packages\\baton\\static\\baton\\app\\src\\fonts\\Dosis-VariableFont:wght.ttf'

**Comment by abidibo** [comment]
Hi @c-vision unfortunately I don't have a window working environment to test and try to reproduce this bug. I guess people could install it in windows, maybe some other user have some hints.

**Comment by abidibo** [comment]
I'm closing this for now.
