### ISSUE TITLE
JS error in demo site

### ISSUE THREAD

**Issue by morlandi** [otto-torino/django-baton#222]
Nice job 👏 

Just wanted to let you know what happens on the demo site (see below). 
Verified with Chrome and Safari.
And yes, I did clear the browser cache 😉 

<img width="1484" alt="Screenshot 2022-08-02 at 15 12 22" src="https://user-images.githubusercontent.com/299854/182383644-ffbecbbd-d992-4ae9-8e57-860acbdc394f.png">

**Comment by abidibo** [comment]
Thanks, now it's fixed
