### ISSUE TITLE
I can't see logout icon.

### ISSUE THREAD

**Issue by donghahaha** [otto-torino/django-baton#239]
![화면 캡처 2022-12-19 145313 (1)](https://user-images.githubusercontent.com/90599433/208357282-114863ee-4500-41b8-b36f-91dff590feff.png)

I made django admin page like above by using django-baton, but I can't find logout icon. ![image](https://user-images.githubusercontent.com/90599433/208357492-1557d36e-c216-4c94-af9c-d4c449c9f5f5.png)
Just "View site" and "Change password".

Does anyone know why this is happening?

**Comment by abidibo** [comment]
Hi @donghahaha which is the url of your logout view?

**Comment by abidibo** [comment]
@donghahaha you just need to upgrade baton, that was fixed in f588af56cb3c2dd6e142b5e2d8cefc007077dcae
