### ISSUE TITLE
StackedInlines with validation errors don't always auto-expand if they use fieldsets

### ISSUE THREAD

**Issue by mikaraunio** [otto-torino/django-baton#240]
When I have a StackedInline with `collapse-entry`, it would be great if any inlines with validation errors could be automatically expanded when the page is reloaded after the user clicked Save.

Right now, the UX is confusing, as "Please correct the error below." is displayed, but no errors are visible on the page until the user expands the inline. And if multiple inlines were edited, finding the one with errors takes extra work.

Alternatively, the collapsed inlines with errors could be colored red, and have an error marker?

**Comment by mikaraunio** [comment]
Looking into this further, it appears this is implemented, but not working 100%. I'm seeing the following:

if the StackedInline uses fieldsets, the inline will auto-expand only if there are validation errors in the fields of the first fieldset.

If the first fieldset is fine, the inline will not auto-expand even if later fieldsets have errors.

**Comment by abidibo** [comment]
@mikaraunio can you provide an example? Fieldsets within inlines? Do you use some third party package?

**Comment by mikaraunio** [comment]
No third-party packages, just basic Django fieldsets. Example below. This inline will auto-expand after save if there was a validation error with `basic_field`, but not if `extra_field` is invalid.

```python
class ItemInline(admin.StackedInline):
    model = Item
    extra = 0
    classes = ('collapse-entry', )
    fieldsets = (
        ('Basic item fields', {
            'fields': (
                'basic_field',
            ),
        }),
        ('Extra item fields', {
            'fields': (
                'extra_field',
            ),
        }),
    )
```

**Comment by mikaraunio** [comment]
It seems this could come from 

```javascript
$(el).parent('fieldset').prev('h3.entry-collapsed')
```

 in `ChangeForm.js`, as the `.prev()` will only match an `h3` directly before the `fieldset` (thus matching only on the first one).

Will try and have a PR pushed shortly.
