### ISSUE TITLE
the exit button does not display on sidebar

### ISSUE THREAD

**Issue by jhoonb** [otto-torino/django-baton#245]
It only displays 'view site' and 'change password'

![image](https://user-images.githubusercontent.com/4448705/228217889-e0d8fc5d-a185-4901-abc3-ceac9c0dad67.png)

I didn't find any settings

**Comment by abidibo** [comment]
Hi @jhoonb can you please add some more information?
- Django version
- Django Baton version
- OS
- Browser
Thanks

**Comment by abidibo** [comment]
I'm closing this, feel free to re-open providing more information
