### ISSUE TITLE
Footer displacement 

### ISSUE THREAD

**Issue by TeraMicro** [otto-torino/django-baton#246]
Hi,

Footer relocates and loses its default position when  'MENU_ALWAYS_COLLAPSED' is  True

How to adjust footer position ?

Thank You

![picture1](https://user-images.githubusercontent.com/126181289/229139347-c8bd997c-7798-43b5-aa12-7a30813d8bbd.png)

Django 3.2
Django-Baton 2.6.2

**Comment by abidibo** [comment]
Hi @TeraMicro ,
this is because the footer is not sticky, in the sidebar not collapsed version it's the sidebar which does the job.

We should change some css to make it sticky, we'll cover this in the next release.
