### ISSUE TITLE
Issue with template

### ISSUE THREAD

**Issue by mariofix** [otto-torino/django-baton#248]
Hello, i just updated the packages for a project and now i have an issue with the template, it adds a link to the top and a lot of space to the bottom

![django-baton-top](https://user-images.githubusercontent.com/5313331/230498300-7f4c97fd-d73c-41df-b13a-8cc5084a67ce.png)

![django-baton-footer](https://user-images.githubusercontent.com/5313331/230498296-955038da-a0c3-474c-bf26-7c701065e32b.png)

I tried with a clean installation of everything and it doesn't go away
I'm using 
Python 3.11.1 on Debian 11
Poetry 1.4.0
Django 4.2
django-baton 2.6.2
django-debug-toolbar 3.8.1 (disabled to check if it was messing with the template)
Should I downgrade in the meantime or might be a config issue?

**Comment by mariofix** [comment]
I downgraded Django to 4.1.8 and it works fine. So there is an issue with Django 4.2 support maybe?

**Comment by abidibo** [comment]
Yeah, Django 4.2 admin templates changed a lot, we're working on this.

**Comment by abidibo** [comment]
@mariofix this was fixed in django-baton==2.7.0
