### ISSUE TITLE
How to set up popup filter? Cannot find templates from documentation

### ISSUE THREAD

**Issue by vladyslav2** [otto-torino/django-baton#254]
Hello!

1. Thank you for such a flexible and well build solution for django admin
2. I'm trying to figure out on how can I adjust filter popup, based on the [docs](https://django-baton.readthedocs.io/en/latest/changelist_filters_includes.html), but I don't see those files anywhere
```
        ('news/admin_filters_include_top.html', 'top', ),
        ('news/admin_filters_include_below.html', 'bottom', )
```
<img width="821" alt="image" src="https://github.com/otto-torino/django-baton/assets/704096/a5aed863-e9db-4e67-a0ba-a81c077b2878">

And in your example app, I also were not able to find them.
Can you please elaborate on how to create popup filters? 

Thank you

**Comment by abidibo** [comment]
Hi @vladyslav2 ,

with this functionality you can inject YUOR templates inside changelist filter section. That means you have to pass the path to the templates you define, it's all up to you.

In the example provided

``` 
('news/admin_filters_include_top.html', 'top', ),
('news/admin_filters_include_below.html', 'bottom', )
```

I had a `news` app and I created 2 templates:

`news/templates/news/admin_filters_include_top.html`

and 

`news/templates/news/admin_filters_include_below.html`
