### ISSUE TITLE
django-select conflict

### ISSUE THREAD

**Issue by randalee** [otto-torino/django-baton#256]
Django-select2(https://django-select2.readthedocs.io/en/latest/)

If using baton, won't be able to use django-select2. 
![image](https://github.com/otto-torino/django-baton/assets/21075211/4571ad72-505d-4ae1-b18f-d72eb058662f)

Modifying base_site.html to change the order of js loading still causes problems: django-select2 only works if you remove the baton.min.js load. 
Is there a good way to get django-select2 to work?

**Comment by abidibo** [comment]
@randalee can you provide an example (repo || codesandbox ||...) with your configuration and usage of select2 please, so it would be easier and faster to look into the issue?

Thanks

**Comment by informatique-bureau-lquancard** [comment]
Hello, i have the same issue, can you help ?
I was using django-jet-reboot, until i found Baton.
But since i setted Baton, my select2 doesn't work anymore.

**Comment by abidibo** [comment]
Please provide a working example to speed up the resolution, thanks

**Comment by abidibo** [comment]
Never mind, was fixed in 2.9.0. Due to Baton re-exporting jQuery.
