### ISSUE TITLE
Menu in multiple admins

### ISSUE THREAD

**Issue by clint74** [otto-torino/django-baton#26]
Is it possible to handle menu in a multi admin once MENU config is centered in settings?

[https://books.agiliq.com/projects/django-admin-cookbook/en/latest/two_admin.html](https://books.agiliq.com/projects/django-admin-cookbook/en/latest/two_admin.html)

**Comment by abidibo** [comment]
I've never thought about it, but I think that no, at the moment is not possible to have different custom menus in different admin sites. Probably it works with no menu configuration (and so with the default menu displayed) overriding and tweaking a bit the [baton admin site](https://github.com/otto-torino/django-baton/blob/master/baton/autodiscover/admin.py) (which as default automatically registers all the applications registered to the base django admin)
