### ISSUE TITLE
Date field rendering

### ISSUE THREAD

**Issue by melicheradam** [otto-torino/django-baton#277]
Hello, I have a custom form, and I want to render the datetime field just as in a regular admin form.

Desired:
<img width="657" alt="image" src="https://github.com/otto-torino/django-baton/assets/20504361/9066acfc-dd81-4406-aaab-9d349d6db707">

`start_time = forms.DateTimeField(initial=datetime.now().isoformat(), help_text="Timestamp in ISO 8601 format", required=True, widget=forms.DateTimeInput(attrs={"style": "width: 300px"}))`

What im getting:

<img width="491" alt="image" src="https://github.com/otto-torino/django-baton/assets/20504361/936b4b4c-c59f-407f-bf60-482498736e40">

What im getting with SplitDateTimeWidget

<img width="801" alt="image" src="https://github.com/otto-torino/django-baton/assets/20504361/08fa5f36-65b2-448f-bb97-ff40d47134d0">

Any help would be appreciated!

**Comment by melicheradam** [comment]
Also, in your test app you are using the rangefilter. When I try to use that, I get the following result:

<img width="497" alt="image" src="https://github.com/otto-torino/django-baton/assets/20504361/775895ad-32e8-4c86-bd7f-aabdc9046e87">

**Comment by abidibo** [comment]
I'm closing this, feel free to re-open providing more info
