### ISSUE TITLE
Admin dashboard display

### ISSUE THREAD

**Issue by tyctor** [otto-torino/django-baton#279]
Hi

i found your admin theme, i and want to try it for our radio admin, currently we are using django-suit, but i want to move forward to responsible admin.

installation looks easy, but something is wrong with dashboard and i dont know where can be problem
it looks somehow shrinked
![Capture 2024-01-23 at 16 52 03](https://github.com/otto-torino/django-baton/assets/44854182/1dd3313e-756a-42f3-a857-115f7b2aa697)

have you any suggestion what i can try to fix?
i am looking forward to answer

**Comment by abidibo** [comment]
Hi @tyctor  , please provide more information:
- Django version
- Django Baton version
- Have you got any custom admin template?
- Have you tried a cache reset?

**Comment by tyctor** [comment]
- Django 4.2.9
- Django Baton 2.9.1
- no custom admin template (just to make sure I removed templates/admin folder but result is same)
- yes tried cache reset and also chrome and firefox browsers, but result is same

when i try to resize browser window in 1024px size it looks differently
![size_1024](https://github.com/otto-torino/django-baton/assets/44854182/0e2f923f-fa07-4303-aa28-84d20ef33e16)

**Comment by abidibo** [comment]
Mmmm never seen that, on Linux, Windows or Mac? Also do you have any custom css in the admin, or any particular admin related installed app?
Difficult to say, if you can reproduce that in a repository I can put my hands on I'll probably figure it out.

**Comment by tyctor** [comment]
it is Linux, i am doing upgrade from Django 3.2 to Django 4.2, i have removed django-suit, so now it should be default Django Admin (templates/css/js), but i will double check that.
good to hear that you never seen that :-) because it will be probably issue on my setup.
thanks for your fast reply i will put comment if i figure it out what cause that issue.

**Comment by tyctor** [comment]
just to confirm that in clean django with django baton install i dont have such issue
