### ISSUE TITLE
Highlighted menu item

### ISSUE THREAD

**Issue by tyctor** [otto-torino/django-baton#280]
Hi

i have defined custom menu
```
{"type": "model", "label": "Events", "name": "punctumradioprogramevent", "app": "punctum_radio"},
{"type": "free", "label": "Calendar", "url": "/admin/punctum_radio/punctumradioprogramevent/calendar/"},
```

problem is that url of `model` entry is similar to `free` entry (`/admin/punctum_radio/punctumradioprogramevent/`) and it seems due to that `baton` is highlighting both menu entries

![Capture 2024-01-24 at 10 49 11](https://github.com/otto-torino/django-baton/assets/44854182/62926462-d37d-4954-9a88-7d6623fe5e22)

how can i solve this?
looking forward to your answer

**Comment by abidibo** [comment]
Hi @tyctor menu free entries can define a `re` property which is a regular expression used to highlight the item, see https://github.com/otto-torino/django-baton?tab=readme-ov-file#free

**Comment by tyctor** [comment]
i think that `free` entry is OK, problem is in `model` entry that should not be highlighdet

**Comment by abidibo** [comment]
Hi @tyctor at the moment the regexp option is available only for free entries. That's because model entries already are matched with a regular expression, because the item should be highlighted both in changelist, changeform and delete page.

**Comment by tyctor** [comment]
and how look regexp that is matching that three url?

**Comment by abidibo** [comment]
It's a path includes:

https://github.com/otto-torino/django-baton/blob/master/baton/static/baton/app/src/core/Menu.js#L306

**Comment by tyctor** [comment]
so it doesnt make sense for me
why
`/admin/punctum_radio/punctumradioprogramevent/calendar/`
is highliding
`/admin/punctum_radio/punctumradioprogramevent/`

**Comment by abidibo** [comment]
Because `/admin/punctum_radio/punctumradioprogramevent/` is included in `/admin/punctum_radio/punctumradioprogramevent/calendar/`

**Comment by tyctor** [comment]
```
const pathRexp = new RegExp(voice.url)
active = pathRexp.test(location.pathname)
```
ok, understand, so my `voice.url` is `model` url `/admin/punctum_radio/punctumradioprogramevent/`, and `location` is `/admin/punctum_radio/punctumradioprogramevent/calendar/`

should not solve this oposite test?

```
const pathRexp = new RegExp(location.pathname)
active = pathRexp.test(voice.url)
```

**Comment by tyctor** [comment]
ok, not `delete` and `change` will not work in that case

**Comment by tyctor** [comment]
ok, i can solve it, if i change `/admin/punctum_radio/punctumradioprogramevent/calendar/` to something else

**Comment by abidibo** [comment]
Exactly, currently the only way to fix this is to choose a free url which does not include the model url

**Comment by tyctor** [comment]
ok, thanks, will do it this way
