### ISSUE TITLE
flex elements not rendering properly in admin

### ISSUE THREAD

**Issue by eddyojb88** [otto-torino/django-baton#286]
Hi,

I tried plugging this package in to my admin dashboard. It seems that flex rows don't render properly. I followed the installation instructions. Any ideas?

<img width="1439" alt="Screenshot 2024-02-23 at 16 34 27" src="https://github.com/otto-torino/django-baton/assets/22086433/2e2c1bda-fa46-46fc-820c-b56a8eb324ba">

**Comment by eddyojb88** [comment]
Ah, I think a found a problematic css:

.dashboard #content {
     width: 600px;
}

unselecting this and the dashboard appears OK but the history elements on the right handside are also clipped. Seems like there are some css conflicts independent on of my code since I have no admin overrides.

**Comment by abidibo** [comment]
Hi @eddyojb88 ,

hard to say without seeing all the code. It never happened before. I don't see how the rule
```width:600px```
could cause that behavior.
My guess is there is some sort of interference between css

**Comment by abidibo** [comment]
I'm closing this, feel free to reopen adding more info
