### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by eddyojb88** [otto-torino/django-baton#287]
How do we remove screen animations, such as the page flash on load or images wobbling?

**Comment by abidibo** [comment]
Hi @eddyojb88 ,

You can remove the image preview animation with something like this in the admin base template:

```
  .baton-image-preview:hover {
      animation: none !important;
  }
```

Regarding the page flash, well, it is necessary, because Baton moves things around and recreates the page layout, and while doing this it hides the page content.
