### ISSUE TITLE
The login form card is too high

### ISSUE THREAD

**Issue by wangyushun** [otto-torino/django-baton#288]
![image](https://github.com/otto-torino/django-baton/assets/24514472/40f19ad7-1371-47f0-b8be-1f79f87e27db)

Normal？The login form card is too high.

**Comment by wangyushun** [comment]
v2.9.0 is ok

**Comment by abidibo** [comment]
Hi @wangyushun ,
no it's not normal. That calculation shouldn't be triggered in login page, I'll look into it, thanks
