### ISSUE TITLE
Fieldset wrapped fields issue

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#29]
If more than one wrapped field group is defined in ModelAdmin in Django2.1, fields are messed up. As in the following :
`fieldsets = (
             ('Fatura Bilgisi',  {'fields': (('tedarikci', 'sozlesme'), 'fatura_no', ('fatura_tarihi', 'fatura_miktari'))}),
             ('Dağıtım Bilgisi',  {'fields': ('merkez_alimi', 'ggm')}),
             ('Ödeme Bilgisi', {'fields': ('hakedis_no','odeme_no', 'faiz_odeme_no', 'banka_hesabi', 'odeme_konusu', 'faaliyet_konusu', 
                                           'faaliyet_detayi', 'odeme_tarihi', 'odeme_miktari', 'butce_kalem_no', 'genel_butce_iade_turu',
                                           'euro_kuru', 'euro_odeme_miktari')}),  
)`

![screen](https://user-images.githubusercontent.com/1778756/61715250-5fad3600-ad65-11e9-81b4-1c71940ae104.jpg)

**Comment by abidibo** [comment]
Hi @AliPolat ,
can you give a try with the develop branch, I think I fixed it.

Thanks

**Comment by AliPolat** [comment]
Thank You. It is working correctly now..
