### ISSUE TITLE
Multiple choice list filter is reset when filter button is pressed.

### ISSUE THREAD

**Issue by piotrw-stepinvest** [otto-torino/django-baton#292]
Steps to reproduce:

- choose one or more options in multiple choice list filter
- press "filter" button (doesn't matter if any other filters are selected or not)
- multiple choice list filter will be cleared and removed from the URL

Looks like the multiple choice filter is missing an input that would be recognised by [filter](https://github.com/otto-torino/django-baton/blob/aa8b489d2cb488c5c6483f0cea287bd08791c88b/baton/static/baton/app/src/core/ChangeList.js#L111) function when constructing the query string.

**Comment by abidibo** [comment]
Hi @piotrw-stepinvest 
thanks for your report, should be fixed in develop branch if you wanna try it.

It will be included in the next baton release.
