### ISSUE TITLE
Rows with only hidden inputs are displayed in admin forms

### ISSUE THREAD

**Issue by jackh-step** [otto-torino/django-baton#295]
Rows containing only hidden inputs in admin forms are being displayed despite having the "hidden" class.
This is related to ["base.css"](https://github.com/django/django/blob/01a4d8a3c741b3129d481ef3515084a199d21222/django/contrib/admin/static/admin/css/base.css#L303) file containing the "hidden" class selector being shadowed.

**Comment by abidibo** [comment]
Hi @jackh-step please provide a sample code with just Model and ModelAdmin. Thanks
