### ISSUE TITLE
Multiple inlines on same tab

### ISSUE THREAD

**Issue by cazgp** [otto-torino/django-baton#3]
Thanks for this awesome module.

Is there a way to put multiple inlines in the same tab?

To work around the limitation in the admin whereby you can't have readonly fields on an inline when you also want to create inlines, I need two inlines pointing to the same model: one to display existing values, and the other to add new ones. It would be great if these could appear on the same tab. Any ideas?

**Comment by abidibo** [comment]
I'm not sure I understood exactly the point here. How can you (without js hacking) avoid the second inline to make fields editable?

Anyway, this is something you can do with custom js. I haven't added support for a js callback when Baton app is ready, and I think I will not add it now, this seems to be a too more particular necessity, which maybe can be addressed in other ways, writing custom views, or custom links in the list_display table which point to the related model insertion.

But, you can do something to get what you want, for example, imagine to have these 2 models:

```
class Stuff(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Stuff"
        verbose_name_plural = "Stuffs"

    def __unicode__(self):
        return self.name


class Item(models.Model):
    stuff = models.ForeignKey(Stuff, related_name='items')
    name = models.CharField(max_length=50)
    description = models.TextField()

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"

    def __unicode__(self):
        return self.name
```

And suppose that the Stuff admin you want a tab containing 2 inlines pointing to the same model Item, one readonly and one not readonly, then you can do something like:

admin.py

```
from django.contrib import admin

from .models import Stuff, Item


class ItemReadonlyInline(admin.StackedInline):
    model = Item
    readonly_fields = ('name', 'description', 'stuff', )
    extra = 0

class ItemInline(admin.StackedInline):
    model = Item
    extra = 0


class StuffAdmin(admin.ModelAdmin):
    list_display = ('id', 'name', )
    inlines = [ItemReadonlyInline, ItemInline, ]

    fieldsets = (
        ('Main', {
            'fields': ('name', ),
            'classes': ('baton-tabs-init', 'baton-tab-inline-items', ),
            'description': 'This is a description text'

        }),
    )

    class Media:
        js = (
            'admin/stuff.js',
        )

admin.site.register(Stuff, StuffAdmin)
```

And all the logic is performed by this javascript function, stuff.js:

```javascript
(function ($) {
    $(document).ready(function () {
        var readOnly = $('#items-group');
        var addNew = $('#items-2-group');
        addNew.css('display', 'none');
        addNew.find('h2').css('display', 'none');
        addNew.find('[id^=items-2]').css('display', 'none');
        addNew.find('#items-2-empty').css('display', '');
        setTimeout(function () {
            readOnly.after(addNew);
            readOnly.find('.add-row').css('display', 'none');
            addNew.css('display', '');
        }, 1000)
    })
})(django.jQuery)
```

I used a timeout function here, because baton doesn't listen for ready events, so it may be necessary for you to adjust its value. You shouldn't have things moving around, though, because the moved elements are set as hidden and shown only at the end of the process.

Pay attention to the js ids: when using two inlines which reference the same model, the second one takes a 2 suffix (i.e. #items-2-group).

You should get something like shown here:

![screenshot from 2018-02-19 15-41-59](https://user-images.githubusercontent.com/444093/36383182-acc7f114-158b-11e8-8d0b-c4dbf6cf06f9.png)

Is this the kind of behaviour you want?

**Comment by cazgp** [comment]
Thanks for the tip and speedy reply!

So I've realised that I actually have quite a lot of use-cases for functionality like this. For example, there is a Person who has "Next of Kin", where the next of kin can have multiple contact details. The person themselves can also have multiple contact details.

In addition to just the address and phone number on the Person, a start date and end date is needed. This is not needed on the next of kin.

## Models

This is shown in the following model:

```
class Person(models.Model):
    next_of_kin_name = forms.TextField()


class Address(models.Model):
    line1 = models.TextField()
    line2 = models.TextField()
    ...


class PhoneNumber(models.Model):
    number_type = forms.TextField()
    type = forms.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    ...


class PersonAddress(Address):
    start_date = models.DateField()
    end_date = models.DateField()


class KinAddress(Address):
    person = models.ForeignKey(Person)


class KinPhoneNumber(PhoneNumber):
    person = models.ForeignKey(Person)
```

## Tabs

I would like tabs like this:

```
| Personal Information | Contact Information | Next of kin |
```

On personal information, display the personal information.

On contact information, display the address and phone number inlines (together).

On next of kin, display the address and phone number inlines (together), as well as the extra field "next of kin name".

## Code

I achieved this so far by adding a `classes` attribute to the model inlines, with the class prefixed with `tab-group-fs-`, and added this to the admin fieldsets.

```
# admin.py
class KinAddressInline(admin.TabularInline):
    model = KinAddress
    extra = 1
    verbose_name = 'Address'
    verbose_name_plural = 'Addresses'
    classes = ('tab-group-fs-next-of-kin', )

        # appended to Admin fieldsets
        ('Next of kin', {
            'fields': ('kin_name', ),
            'classes': ('tab-fs-next-of-kin', ),
        }),
```
Then the javascript is:

```
(function($) {
    $(document).ready(function() {
        function createTabGroups() {
            // Find all elements on the page that have a class starting with "tab-group"
            const elements = Array.from(document.querySelectorAll('fieldset[class*="tab-group-"]'))

            // Store the tab content parent and the nav tabs as we'll be using it a bit
            const tabs = $('#content-main .tab-content')
            const navTabs = $('#content-main .nav-tabs')

            // Loop through all the tabs and move them to their correct data tab
            elements.forEach(element => {
                const name = Array.from(element.classList).filter(name => name.startsWith('tab-group'))[0].replace('tab-group-', '')

                // Ensure the content is correct / styled nicely
                const tab = $(tabs.find('#' + name))
                $('<div class="tabular inline-related">').append(element).appendTo(tab)

                // Ensure the nav tab has the correct name
                const navTab = navTabs.find('a[href="#' + name + '"]')
                if (!navTab.text()) {
                    navTab.text(name.replace(/[_-]+/g, ' ').replace(/^(\w)/, match => match && match[0] && match[0].toUpperCase()))
                }
            })
        }

        // Wait for the nav tabs to appear
        const poller = setInterval(function() {
            const element = document.querySelector('#content-main .nav-tabs')
            if (element == false) {
                return
            }
            clearInterval(poller)
            createTabGroups()
        }, 100);
    });
})(django.jQuery);

```

## Final thoughts

Do you think there's space for this in the main code-base (obviously with way less hacky code than this!)

If so, I'm willing to put something in a PR :)

**Comment by abidibo** [comment]
Ok, I see,
I'll think about it, at this moment tabs do not support a sort of grouping, there is no super-structure which can allow for grouping fieldsets or inlines, but I'll think about it in the next days. Maybe I can add this feature, stay tuned

**Comment by cazgp** [comment]
As a user of my own hack (!), adding classes to the inlines and the fieldsets is fairly consistent with the existing API and isn't that tricky. It's made further extensions to the admin pretty quick.

The only thing is, that doesn't allow for ordering the inlines and the fields. The fields would always come first, and then the inlines would. If you wanted something different from that, then the classes trick doesn't work. And that also defeats the object of this plugin, which is the ability to order things in any which way.

Let me know if you come up with anything and we can work on a PR. More than happy to review / discuss ideas.

Cheers!

**Comment by cazgp** [comment]
Hey! Thanks so much for this. It sounds like it address my concerns.

One thing -- I'm not quite sure I fully understand the "--" thing. Can you explain in more detail how that works?

Otherwise, go ahead!

**Comment by abidibo** [comment]
Yes,

the double hype just acts as a separator. A separator between elements which should be grouped inside one tab. Each element can be an inline or a fieldset, so you can have for example:

`'baton-tab-group-fs-main--inline-items--fs-location--inline-contacts'`

where a single tab is created which will contain in the given order:

- the fieldset fs-main
- the inline items
- the fieldset fs-location
- the inline contacts

The title of the group tab will be the first element title, in this case the title of the main fieldset.

**Comment by cazgp** [comment]
Cool, that all makes sense. I don't have time right now to test, but do you feel like merging and we can see what happens?

**Comment by abidibo** [comment]
I'll merge soon, already done in develop branch but still not pushed. I'm adding also support for text input fields in filters and some styles to the results list table, soon I'll release the v1.1.0. Cheers!
