### ISSUE TITLE
Django AdminModel date_hierarchy

### ISSUE THREAD

**Issue by diogosimao** [otto-torino/django-baton#31]
Hi,

Would it be pertinent to use `date_hierarchy = 'created_at'` and wait for side by side (inline) date values?
![image](https://user-images.githubusercontent.com/8460840/71192756-aac16b80-2267-11ea-92fa-5c411e47fb52.png)

As the number of items (date values) expands the list of link, theses items on the top of the page pushes the important content lower than it should or could be.

see default **Django Admin**:

![image](https://user-images.githubusercontent.com/8460840/71193158-68e4f500-2268-11ea-9a8d-95e203c2a2ed.png)

see **baton**:

![image](https://user-images.githubusercontent.com/8460840/71193214-81550f80-2268-11ea-94d5-a6833455c2d1.png)

Any ideas of how can I customize it?

**Comment by abidibo** [comment]
Hi,
thanks for reporting this.

> Would it be pertinent to use date_hierarchy = 'created_at' and wait for side by side (inline) date values?

Sure,
I'll add styles for it stay tuned

**Comment by abidibo** [comment]
@diogosimao ,
I fixed it in the development branch.

Can you give it a try and give me some feedback? If you're satisfied with the result, I will release an hotfix
