### ISSUE TITLE
Custom date widget

### ISSUE THREAD

**Issue by diogosimao** [otto-torino/django-baton#32]
Hi,

Is there anything related to custom _datetime_ fields widgets on _list_editable_. Posting baton and default django admin:

**(1)**
![image](https://user-images.githubusercontent.com/8460840/71287573-791fd180-2347-11ea-9fe5-a96383ed6994.png)

**(2)**
![image](https://user-images.githubusercontent.com/8460840/71287613-95bc0980-2347-11ea-90a3-5cc6e781fa71.png)

**(3)**
And here we see date picker popup after clicking:
![image](https://user-images.githubusercontent.com/8460840/71287720-dfa4ef80-2347-11ea-8ac2-4248ace7bb1c.png)

Thanks!

**Comment by abidibo** [comment]
Thanks for reporting this,

it has been fixed in the develop branch, will be included in the next release
