### ISSUE TITLE
Calendar in admin inline - bad placing

### ISSUE THREAD

**Issue by pyutil** [otto-torino/django-baton#34]
Hi, thank you for your great work.

![calendar_wrong_place](https://user-images.githubusercontent.com/59448376/72244865-74b9a200-35ef-11ea-8354-e1845be26161.png)

The calendar doesn't appear near to date/calendar icon but at the right corner (at the end of the inline). When browser content is not resized then calendar is not visible at all.
(I have tested same with current both branches: master, develop.)

**Comment by abidibo** [comment]
Hi @pyutil ,
thanks.
Try again with the develop branch, should be fixed now.
I'll also restyle the calendar in the next future, I don't like it very much as it is now.

**Comment by pyutil** [comment]
Hi, you are extremely fast !!!
It works excelent now.
(but I have few such small things here.. :) can I add them?)

**Comment by abidibo** [comment]
yeah sure, add all issues
