### ISSUE TITLE
colored inline header hasn't full size

### ISSUE THREAD

**Issue by pyutil** [otto-torino/django-baton#36]
This is really minor.
If the inline is too wide, then inline header is not so wide.
See the picture (text of the header is not visible, i'm sorry): the pink(?) color is the header. It should have the full page width.

(I'm sorry that I am so slow. And I must change my statement, we have no errors more. Only maybe some wishes - design features. I will add one later today. Thanks.)
![inline_header](https://user-images.githubusercontent.com/59448376/72898437-602e8580-3d24-11ea-93d5-490457858c98.png)

**Comment by abidibo** [comment]
Yeah, I know this one, not easy to fix btw. I'll look more into it.

**Comment by abidibo** [comment]
As a general rule, use `StackedInline` if `TabularInline` causes overflow, I know they keep much more space, but this is their purpose

**Comment by pyutil** [comment]
Maybe I understand the problem of difficult styling: that the header and the inline itself are not in common container element.
No problem. This is really not important thing.
