### ISSUE TITLE
design feature: could textareas take more width?

### ISSUE THREAD

**Issue by pyutil** [otto-torino/django-baton#37]
In the pictures are situations where textareas could be wider.
Maybe similar problem is that "select" and text "input" could have same size.
![textarea_width_1](https://user-images.githubusercontent.com/59448376/72898750-f6fb4200-3d24-11ea-8491-4192d783ee59.png)
![textarea_width_2](https://user-images.githubusercontent.com/59448376/72898766-fc588c80-3d24-11ea-88e1-d6a0ec2f17bc.png)

**Comment by abidibo** [comment]
You can easily make them wider with a single css rule in your admin base template, also textarea are resizable.

Input text width is set to auto, to avoid having default bootstrap 100% wide inputs, so it would be difficult to have textareas and inputs of the same width, unless I force them, and I'm not sure this would be a good idea right now

**Comment by pyutil** [comment]
Hi. Thank you. I mean same width for <input> and <select>.
For <textarea> would be good the maximum width. So I will try resize them, but I am not very good in css.
Thank you for your whole work!

**Comment by pyutil** [comment]
("input", "select" was hidden from github formatting - my mistake).
But I see from the attached pictures that "select" have different sizes. Probably from their contained options?
So maybe it would be difficult and contraproductive to normalize their sizes. And it is not very important.
But the max-sized "textarea"s would be great.

**Comment by abidibo** [comment]
Hi,
yes, you shouldn't control select width, because it auto sizes itself basing upon its contents. If you set a fixed width you risk in some browsers to have the contents cut off.

> But the max-sized "textarea"s would be great.

I don't get the point here, you need to have wider textareas?

**Comment by pyutil** [comment]
Yes. I think it would be good if textareas will take all possible width (without need of resizing them).
This was the most imprortant thing in this issue.
In the attachement:
- could the 3 textareas in the top take 1/3 of the full width? (instead of 60% of 1/3)
- could the textarea called "Popis" take the rest of the width to the right margin? (instead of 60% of the free area)
If it is easy, it would be good.
If you see some problem why not style it globally inside your package, I will try style it myself.

**Comment by abidibo** [comment]
I prefer not to have textarea at 100% width, because it seems excessive to me with full hd screens,

But you can try to add this simple stuff in the `block extrahead` of your base admin template:

```
<style>
  textarea {
    flex: 1 !important;
  }
</style>
```
