### ISSUE TITLE
Setting 'SITE_HEADER' not working on Django==3.0.3

### ISSUE THREAD

**Issue by manuelfedele** [otto-torino/django-baton#41]
I've set everything as described
- `'baton'` in installed apps before 'django.contrib.admin'
- `'baton.autodiscover'` at the end of installed apps
- included baton's urls in urls.py

But setting
```
BATON = {
    'SITE_HEADER': 'MyAdminName'
}
```
in settings.py does not change my admin name. Is a fresh started django project with just 4 models. everything else seems to work fine.

At the moment I'm overriding `admin.site.site_header` as workaround.

(Same behavior with `'INDEX_TITLE'`)

**Comment by abidibo** [comment]
Hi @manuelfedele ,

I cannot reproduce the bug you're talking about, see screenshot below.
I've tested with django==3.0.3 and django-baton==1.5.7

![Screenshot from 2020-02-24 14-07-19](https://user-images.githubusercontent.com/444093/75154948-398eb080-570f-11ea-8402-8c32b1a5fb1b.png)

Can you set up a repo which reproduces the error?

**Comment by manuelfedele** [comment]
I'll do it asap. :)

**Comment by kwangsooshin** [comment]
@manuelfedele Are U add `from baton.autodiscover import admin` in urls.py?

**Comment by manuelfedele** [comment]
@kwangsooshin I did not and I think that was the issue. I just noticed that was written even in the docs. I feel dumb. :)
