### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by nitishxp** [otto-torino/django-baton#42]
Hi, @abidibo I am facing UI issues on all pages.

![image](https://user-images.githubusercontent.com/25002490/75271289-f709c880-5821-11ea-8ff9-8e89023f5764.png)

![image](https://user-images.githubusercontent.com/25002490/75273115-67661900-5825-11ea-8ddd-902f4b8a45cb.png)

![image](https://user-images.githubusercontent.com/25002490/75273144-7baa1600-5825-11ea-98b1-6b0a0aa4a9f0.png)

**Comment by nitishxp** [comment]
1.

**Comment by neowenshun** [comment]
Hi im facing the same issue how did u resolve this?
