### ISSUE TITLE
Put each inline to seperate tab

### ISSUE THREAD

**Issue by nitishxp** [otto-torino/django-baton#43]
Hi @abidibo 

```
@admin.register(AModel)
class AuthorAdmin(admin.ModelAdmin, DynamicArrayMixin):
    list_display = ('name',)
    inlines = [BAdmin, QGenericForeignKeyInline, ]

```

I am using the above code in admin.py. AModelconsists of 23 fields. I want to have separate tab for each of the inlines classes. I tried following your documentation but I need to explicitly mention all fields in the fieldset values. 

I am also using GenericForiegnKey named QGenericForeignKeyInline but this is not coming in separate tab even I am attaching a class to it. It seems it only works in ForeignKey.

**Comment by linhnvhicts** [comment]
If you can understand how the syntax work then it's much easier to set up tab contents
```
@admin.register(AModel)
class AuthorAdmin(admin.ModelAdmin, DynamicArrayMixin):
    list_display = ('name',)
    inlines = [BAdmin, QGenericForeignKeyInline, ]

    fieldsets = (
        ('General', {
            'fields': ('your main model fields',),
            'classes': ('baton-tabs-init', 'baton-tab-group-fs-badmin--inline-badmin_related_name', 'baton-tab-group-fs-QGenericForeignKeyInline--inline-QGenericForeignKeyInline-related_name', ),
        }),
        ('BAdmin', {
            'fields': (),
            'classes': ('tab-fs-badmin', ),
        }),
        ('QGenericForeignKeyInline', {
            'fields': (),
            'classes': ('tab-fs-QGenericForeignKeyInline', ),
        }),
    )
```

**Comment by nitishxp** [comment]
@linhnvhicts any idea how to pass all the fields of main model since I have indefinite no of columns in the model?

**Comment by abidibo** [comment]
@nitishxp there isn't an "easy" way of doing it, no `all` keywords or such. The presence of a fieldset is required, because I nedd a css class to be defined in order to move `divs` around after page creation.

Maybe you can construct a tuple of all fields with introspection: 
https://stackoverflow.com/questions/3106295/django-get-list-of-model-fields

**Comment by nitishxp** [comment]
@abidibo how to use in Generic Foreign Key? since generic foreign does not have any related name?

**Comment by abidibo** [comment]
@nitishxp Have you got an example app I can try?

**Comment by nitishxp** [comment]
@abidibo give me some time to prepare demo app?

**Comment by abidibo** [comment]
@nitishxp thanks, I appreciate, because I'm quite busy these weeks

**Comment by nitishxp** [comment]
@abidibo  https://github.com/nitishxp/abidibo

**Comment by nitishxp** [comment]
Got a hack used <appname>-<model-name>-content_type-object_id as related name it worked

**Comment by abidibo** [comment]
@nitishxp cool.

**Comment by nitishxp** [comment]
@abidibo In case of non-fields errors, the UI is not looking great could u resolve it.

![image](https://user-images.githubusercontent.com/25002490/75627035-9815cc00-5bf2-11ea-88e4-7af5707a086a.png)
