### ISSUE TITLE
Sidebar Menu not following Django index.html template ?

### ISSUE THREAD

**Issue by linhnvhicts** [otto-torino/django-baton#44]
I tried to add a link  name `Transactions History` under an app by overriding index.html :

            {% for model in app.models %}
                <tr class="model-{{ model.object_name|lower }}">
                {% if model.admin_url %}
                    <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
                {% else %}
                    <th scope="row">{{ model.name }}</th>
                {% endif %}
    
                {% if model.add_url %}
                    <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
                {% else %}
                    <td>&nbsp;</td>
                {% endif %}
    
                {% if model.admin_url %}
                    {% if model.view_only %}
                    <td><a href="{{ model.admin_url }}" class="viewlink">{% trans 'View' %}</a></td>
                    {% else %}
                    <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
                    {% endif %}
                {% else %}
                    <td>&nbsp;</td>
                {% endif %}
                </tr>
            {% endfor %}
            <tr class="model-{{ model.object_name|lower }}">
                <th scope="row"><a href="{% url 'backend.transactions'%}">Transaction History</a></th>
                <td><a href="{% url 'backend.transactions'%}" class="viewlink">{% trans 'View' %}</a></td>
                <td>&nbsp;</td>
            </tr>

And the link did show under the main page:

![Screen Shot 2020-03-20 at 11 59 16 AM](https://user-images.githubusercontent.com/46511495/77137892-4a2e0e80-6aa2-11ea-8bbe-72daf5b98c93.png)

But the sidebar menu not getting updated:

![Screen Shot 2020-03-20 at 11 59 21 AM](https://user-images.githubusercontent.com/46511495/77137902-54e8a380-6aa2-11ea-8c93-0c07ecae9cf4.png)

I know that i can add link with Menu settings but it would required to re write each app in menu, i would love to just add a new section under the app of sidebar menu, are there any way to do it  without rewriting every app in menu ?

**Comment by abidibo** [comment]
Hi @linhnvhicts ,
I'm sorry but no, there is no way the baton menu can get data from an html section you add to a template. Baton menu is constructed from the admin registered apps and at the moment it's not possible to specify just some additions, you need to construct your full menu tree.

**Comment by linhnvhicts** [comment]
Thank you for the reply, i understand that the menu should follow the models so i decided to just to rewrite the menu :)
