### ISSUE TITLE
May I change fonts?

### ISSUE THREAD

**Issue by kwangsooshin** [otto-torino/django-baton#45]
Hi, I want to chnage fonts in baton(because of support korean).
May I change font settings?

**Comment by abidibo** [comment]
Hi, yes two ways:

1 - override the baton `base_site.html` template and add the followind snippet:
```
<style>
html,
body,
button,
input,
optgroup,
select,
textarea {
  font-family: arial; /* change at your will */
}
</style>
```
And if you see some other html elements with the `Dosis` font, just add it to the list.

 2 - change the font setting in the `_variables.scss` file of baton (`baton/static/baton/app/src/styles/`) and recompile the app, then serve the compiled js from an app declared before baton (this is explained in the documentation)

**Comment by kwangsooshin** [comment]
Thank you!
