### ISSUE TITLE
Menu not showing in Django 2

### ISSUE THREAD

**Issue by farooqaaa** [otto-torino/django-baton#46]
If you use Baton's `admin.site.urls` in _urls.py_, the menu doesn't show. This can be fixed by using Django's admin URLs. I think this should be mentioned in the docs.

**Comment by abidibo** [comment]
It's not clear to me, can you elaborate more please?

**Comment by abidibo** [comment]
I'm closing this for now, not a bug and the application works as expected when following the installation instructions
