### ISSUE TITLE
Code editor 

### ISSUE THREAD

**Issue by neowenshun** [otto-torino/django-baton#58]
Im currently using the codemirror-2 editor , does not seem to be compatible in this case

**Comment by abidibo** [comment]
Hi @neowenshun ,
I usually use django-ckeditor. Maybe the problem is that the editor js should be delayed a bit. If you provide a runnable example I can give it a try.

**Comment by neowenshun** [comment]
Hello , i have decided to remove the code editing functionality from my django admin , sorry for the trouble
