### ISSUE TITLE
Customizing the UI

### ISSUE THREAD

**Issue by neowenshun** [otto-torino/django-baton#59]
Hello , i have am trying to change the css of the page but im having troubles with the recompiling method. Im using windows 10 and i have npm installed. 

I cant seem to run the command 'npm run compile' It would have a '.' not a recognized command error , it seems that ./ does not work in a windows environment.

After switching to .\\ the command has another error , ELIFECYCLE err appears .

Sorry im a real noob , would appreciate your help!

**Comment by neowenshun** [comment]
Hello , sorry i have managed to get npm compile to work , however im still unable to override the css . The instructions said to place baton after one of my django apps , which i did . However i do not quite understand how this work . Im serving my app frontend with reactjs  therefore there is no static folder within my app , but i do have one in my project root directory from running the command collect static. I have tried replacing the baton.min within static folder of django-baton (in side the root directory)  however that does not change the css at all . Would appreciate your help!

**Comment by abidibo** [comment]
Hi @neowenshun ,
I don't know your project structure, but probably the admin works differently from your frontend stuff.
You need to know how django picks up static files. It serves the first file it finds with a given path, searching in all static directories inside apps, in the order the installed apps are declared (the same happens with a collectstatic and serving the static files directly from a webserver). So you need to compile the files and place them inside a static folder of an app declared before baton.

So, imagine you have an app called `core`, then you have to declare it before `baton` in the installed apps. Then you need to place the compiled js here: `core/static/baton/app/dist/baton.min.js`
