### ISSUE TITLE
Static files loading are failed when I use S3 storage

### ISSUE THREAD

**Issue by kwangsooshin** [otto-torino/django-baton#60]
Hi,

When I use baton with S3 storage, I see some problems with the static files.

Some of the fonts and icons paths are  not correct such as:

```
app-nginx_1  | 2020/06/15 04:28:51 [error] 8#8: *540 open() "/django-static/baton/app/dist/b128f9e98de1bbea51b7e650e6a6e3c7.ttf" failed (2: No such file or directory), client: ***.***.***.***, server: ***.***.***.***, request: "GET /static/baton/app/dist/b128f9e98de1bbea51b7e650e6a6e3c7.ttf HTTP/1.1", host: "***.***.***.***:****", referrer: "http://***.***.***.***:****/admin/"
```

**Comment by abidibo** [comment]
If only font files have such problems it doesn't sound like a baton bug for me. Maybe some misconfiguration of S3 for different mime types or something similar? (I've no much experience with S3 storage).

![baton-fonts](https://user-images.githubusercontent.com/444093/84775564-ac35db80-afdf-11ea-8bc0-10b615702030.png)

In this screenshot you see the path of fonts files in a production site, the path is correct and files are served from the web server at that exact location.

**Comment by kwangsooshin** [comment]
Some of icons also broken such as (+add) and (ㅁchange) buttons.

**Comment by abidibo** [comment]
> Some of icons also broken such as (+add) and (ㅁchange) buttons.

If the font files aren't loaded properly, then this is an expected behaviour

**Comment by kwangsooshin** [comment]
Okay, I close this issue when I figure out reason of this problem. Thanks!
