### ISSUE TITLE
Hide the "Menu" rectangle

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#63]
Hi again,
Is there a way to hide the "Menu" rectangle that is displayed in between the INDEX_TITLE and the list of menu items?
I mean this guy:
<img width="191" alt="Screen Shot 2020-06-20 at 5 20 44 PM" src="https://user-images.githubusercontent.com/1315554/85211771-7152e100-b31a-11ea-912b-1961e1352887.png">
It takes quite some space and it's pretty obvious that this part of the page is the menu, so I'd like to skip it.
Thanks!

**Comment by etanter** [comment]
solved that with a violent css hide: `.sidebar-menu h1 { display: none }`
probably an option would be nicer, but meanwhile that will do!

**Comment by abidibo** [comment]
Yes, this is the way to do it now, I'll add an option in the next release
