### ISSUE TITLE
can first tab be an inline?

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#64]
Hi again,

I'd like to have a model change page that consists of 4 tabs, the first of which is from an inline. 

The only thing I manage to do is to create a fake fieldset whose `classes` attribute contains the proper ordering of the tabs. But of course, this means I have this first extra/empty tab as the landing of the page. (and so I end with 5 tabs instead of 4)

Is that possible? 

Thanks!

**Comment by abidibo** [comment]
Hi @etaner,
addressed in the develop branch. 
You can now add an `order-[NUMBER]` class to the first fieldet, which specify its order in the tabs. Order starts from 0. All the other tabs respect the order of declaration:

```
classes: ('order-1', 'baton-tabs-init', '...')
```

But at least one fieldset should exist, or you'll need to create a fake one in any case.

**Comment by etanter** [comment]
I think there's a slight glitch: I have one real fieldset, which uses `order-3` to go last (4 tabs), and specifies the inlines for the three first tabs. When I first load the page however, the content of the first tab is that last tab! if I go to any other tab and back, it displays fine (the expected inline).
(I checked and the url is "clean", `...path.../id/change`)

**Comment by etanter** [comment]
in fact even if I load `...path.../id/change/#inline-xxx` directly in the browser, it displays the wrong body.

**Comment by etanter** [comment]
works fine now, thanks!
