### ISSUE TITLE
collapse individual stackinline element

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#65]
Hi again again,

While the style of Baton is very elegant, it is quite space consuming. When one has to display a number of inline objects with StackInline, it quickly gets huge.

With the `collapse` class in the Inline one can have the whole set of elements collapsible, but that doesn't really make it better: when looking for one element, one has to expand the whole set.
Would it be possible for you to add a per-element collapse/expand button? 

This way one could see the summaries of all the elements, and expand only the one to edit/inspect.

Thanks!

**Comment by abidibo** [comment]
Addressed in develop branch, will be released today. Just add a `collapse-entry` class:

```
class VideosInline(admin.StackedInline):
    model = Video
    extra = 1
    classes = ('collapse-entry', )
```

**Comment by etanter** [comment]
Great, looking forward to the release! Thanks
