### ISSUE TITLE
Django-filer minor styling incompatibility.

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#67]
Below is a sample Admin Change Page :

![Admin Change Page](https://user-images.githubusercontent.com/1778756/85298105-5617db00-b4ac-11ea-95ac-088b6d7a1185.PNG)

Any suggestion ? Thank you in advance.

python 3.6
django 2.2
django-filer 1.7.1.1
django-baton 1.7.6

**Comment by abidibo** [comment]
I always use filer inside muy projects, but I don't use the custom fields. I'll look into it to see if can be easily addressed.  Django filer overrides many django templates and changes the default styles a lot, too much IMHO. 
I'll see what I can do about it.
