### ISSUE TITLE
wrong body when first tab is an inline

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#69]
Related to #64:
There's a slight glitch with the new feature. 
I have one real fieldset, which uses `order-3` to go last (4 tabs), and specifies the inlines for the three first tabs. When I first load the page however, the content of the first tab is that last tab! if I go to any other tab and back, it displays fine (the expected inline).
(I checked and the url is "clean", `...path.../id/change`
in fact even if I load `...path.../id/change/#inline-xxx` directly in the browser, it displays the wrong body.)

any idea?

thanks!

**Comment by abidibo** [comment]
yeah, definitely a bug, I'll fix it very soon

**Comment by abidibo** [comment]
fixed in baton 1.8.5
