### ISSUE TITLE
Search button in admin listview

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#7]
Hi,

Search button in admin listviews do not display any visual clue that it is hovered by mouse. 

Thank you

**Comment by abidibo** [comment]
Hi, this is a minor bug, which does not justify an hotfix release, in my opinion. Will fix when solving other issues.
Meanwhile you can fix it by adding a simple css rule in the `base_site` admin template (create one in an app declared before baton if you don't have it):

    <style>
        #changelist-search input[type="submit"]:hover {
            background: #fafafa; /* change color at your will */
        }
    </style>
