### ISSUE TITLE
from suit to baton: suit_form_includes

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#71]
I'm almost done with migrating my app from suit to baton. Just two pending issues. Here's the first.

Suit has a mechanism for the admin called `suit_form_includes`, which makes it possible to add fieldsets specified by arbitrary templates. See https://django-suit.readthedocs.io/en/develop/form_includes.html
(note that these can be used in combination with form tabs)

I haven't found a way to mimic this in baton. Is that possible already? 
If not yet, would it be possible for you to add it?

Thanks!

**Comment by abidibo** [comment]
Actually this goes against baton's philosophy: "overwrite as few django templates as possible".
There is no way to add this functionality if not tweaking the `change_form` template. And that's exactly how you can do the same thing, not very handy, I admit.

**Comment by etanter** [comment]
ok, thanks, I'll figure out some other way to do it.

**Comment by abidibo** [comment]
@etanter ,
I finally decided to add such functionality, a bit differently though.
As you know, I don't want to modify the original template, but I found a way to just add something at the end of the template without messing with the change form template internals.

Will be released today with the version 1.9.0
