### ISSUE TITLE
from suit to baton: suit_row_attributes

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#72]
Hi, 
so here's the second thing I'm missing during my migration from suit to baton. 
I'm afraid it might suffer the same fate as the first, but let's see ;)

Suit has this `suit_row_attributes` mechanism:
https://django-suit.readthedocs.io/en/develop/list_attributes.html?highlight=suit_row_attributes#list-row-attributes
which makes it easy to apply object-specific formatting in change lists.

Any idea how to do/add that to baton?

Thanks

**Comment by abidibo** [comment]
Hi @etanter ,
well, in the end, I've decided to implement the form includes functionality because I think it' very useful in some cases, and I found a way to do it without messing too much with the template. You can find the documentation in the Readme.
While for this issue, It's a bit harder to add this functionality without being too rude. I don't think I'll add it at the moment, I always use other ways to point up errors or stuff in a table row (a dedicated column with icons for example).

**Comment by etanter** [comment]
Hi @abidibo,
Cool for the form includes! For the row attributes, I understand. I could indeed use a column with icons. Btw, I can't manage to force a column width in the change_list to be exactly the width of the icon, and nothing more. 
Setting the width in CSS as follows:
```
.change-list .results  table > thead > tr > th.column-registered { width: 10px; }
```
only forces the column to have fixed width (which is good), but it's way larger than 10px (in fact the value I put here seems to have no impact at all, even if I put `!important`). 
Any idea on how to address this? (I realize this might not have to do with baton proper...)

**Comment by abidibo** [comment]
> Hi @abidibo,
> Cool for the form includes! For the row attributes, I understand. I could indeed use a column with icons. Btw, I can't manage to force a column width in the change_list to be exactly the width of the icon, and nothing more.
> Setting the width in CSS as follows:
> 
> ```
> .change-list .results  table > thead > tr > th.column-registered { width: 10px; }
> ```
> 
> only forces the column to have fixed width (which is good), but it's way larger than 10px (in fact the value I put here seems to have no impact at all, even if I put `!important`).
> Any idea on how to address this? (I realize this might not have to do with baton proper...)

that probably depends on the width of the column header text. The amount of text controls the column width if does not fit in the desired width. Also the `.text` element which wraps the header anchor has some right padding to make space for the sorting icons, you need to remove it 
```
.change-list .results  table > thead > tr > th.column-registered .text { padding-right: 0px; }
```

**Comment by etanter** [comment]
Great, thanks!!

**Comment by etanter** [comment]
ok, coming back to this: I'm trying to get the width of a column to match an icon, and nothing more.
Here's what I have:
![image](https://user-images.githubusercontent.com/1315554/85755246-c48eb000-b6db-11ea-93c5-efd25ee2dba5.png)
despite the fact that the header has an empty string title, and that the content is really just the pic (I also tried with just a letter 'X', same result).
In CSS I'm setting the padding right to 0 as you suggested, and setting a width of 1px (so the resulting width at least is fixed). But the picture above is the best I can get, while I'd really like it to be just the width of the icon.
do you know how this can be achieved?

**Comment by etanter** [comment]
if I put `padding: 0px !important;` then the icon is really stuck to the border on the left (good), but the right remains too wide:
<img width="38" alt="Screen Shot 2020-06-25 at 12 07 00 PM" src="https://user-images.githubusercontent.com/1315554/85755930-61514d80-b6dc-11ea-9b88-8f592d872e1a.png">

**Comment by abidibo** [comment]
![Screenshot from 2020-06-25 18-13-41](https://user-images.githubusercontent.com/444093/85757289-a04cc680-b70f-11ea-8574-873e12886b6e.png)

```
.change-list .results  table > thead > tr > th.column-registered {
  width: 10px;
}
.change-list .results  table > thead > tr > th.column-registered .text {
  display: none;
}
```

These rules do the job for me

**Comment by etanter** [comment]
yup, it works! Thanks again!
