### ISSUE TITLE
html tooltips not showing

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#74]
Hi,
I just realized that the tooltips I have on some table elements are not showing since I migrated to baton.
Those are simple `title=` attributes on the html elements, like `td`.
How do I get these to show?
thanks!

**Comment by abidibo** [comment]
More info needed, how do you set such title attributes? It seems to work for me:

![tooltip](https://user-images.githubusercontent.com/444093/85828399-9e731980-b788-11ea-95e0-015e1638fa02.png)

![Screenshot from 2020-06-26 08-39-37](https://user-images.githubusercontent.com/444093/85828385-987d3880-b788-11ea-92c9-053709d68bf4.png)

**Comment by etanter** [comment]
I do the same, with the title attribute:
<img width="422" alt="Screen Shot 2020-06-26 at 7 59 36 AM" src="https://user-images.githubusercontent.com/1315554/85854754-fdce2b00-b782-11ea-8ff4-72d8337f60a2.png">

**Comment by abidibo** [comment]
No idea, baton doesn't do anything with title attributes. You should set up a working example which reproduces the error.

**Comment by etanter** [comment]
ok, I'll keep trying to figure out what's going on.

**Comment by abidibo** [comment]
I've activated bootstrap tooltips on all `[title]` elements. Also `Baton` js object instance has a `loadTooltips` method which can be called to refresh tooltips if any are added after page load

**Comment by etanter** [comment]
it works now! excellent!! thanks again^n ;-)
