### ISSUE TITLE
messagelist margin bottom

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#75]
Hi, 
When successfully saving an object, the admin displays a message, which is displayed with a weird white margin:
![image](https://user-images.githubusercontent.com/1315554/85787393-52c55f00-b6f9-11ea-8917-5ab641d22698.png)
I've tried to play around with css to make it disappear, but to no avail. 

I can make it bigger!
```
.messagelist .success {
  margin-bottom: 10rem !important;
}
```
but putting `0rem` makes the actual margin disappear (I can see that with the chrome dev tools), but the rendering is the same. It seems that the observed space is coming from the parent container div, which has `header`, `messagelist`, and `contained-fluid`, but I don't see any attribute there that I could tweak.

Any idea on how to avoid that space?

Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,

can you provide more info, or a larger screenshot, I don't get where this happens:

![Screenshot from 2020-06-26 08-35-57](https://user-images.githubusercontent.com/444093/85828208-24429500-b788-11ea-9a35-ad59d8301dcc.png)

**Comment by etanter** [comment]
Here it goes. I noticed that it's displaying on the whole width of the page instead of just below where the breadcrumbs would be (I comment these out in the templates).

![image](https://user-images.githubusercontent.com/1315554/85855145-c6ac4980-b783-11ea-9d75-64309244bf29.png)

**Comment by abidibo** [comment]
@etanter  this shouldn't happen with the django default templates. It's the same thing that happens with django-filer.
Have you got any custom template?

**Comment by etanter** [comment]
yeah, quite a bit... I'll investigate which template is causing the problem

**Comment by abidibo** [comment]
Baton moves the messagelist div after the `#content > h1` title. In django filer such `h1` is missing. Maybe your problem is similar

```
$('#content > h1').after($('.messagelist'))
```

**Comment by abidibo** [comment]
![Screenshot from 2020-06-26 14-45-37](https://user-images.githubusercontent.com/444093/85858333-c039c400-b7bb-11ea-971b-61c7e7ff9b09.png)

The title is "select news to change"

**Comment by etanter** [comment]
I solved it by moving the block `messages` in the base template to into the `content` div. 
not sure why it wasn't there in the first place, but now the messagelist displays within that part (instead of the whole width), and has no weird border.
Thanks for pointing me to the right place!

**Comment by abidibo** [comment]
ok that's a solution, but if you have a #content>h1 element, then baton moves it for you

**Comment by etanter** [comment]
yeah, indeed, that h1 is commented out (I'm using several tweaks to make the style more compact, so no breadcrumbs, no "Menu" box on the sidebar, etc. - and that content/h1 is commented out for the same reason)
