### ISSUE TITLE
baton 1.8.5 add div box around each field in admin ?

### ISSUE THREAD

**Issue by linhnvhicts** [otto-torino/django-baton#76]
I recently upgrade baton from version `1.5.8` to `1.8.5` and these background boxes start appearing around each field on the change form

version 1.5.8:

![Screen Shot 2020-06-26 at 11 53 57 AM](https://user-images.githubusercontent.com/46511495/85821921-dd629880-b7a3-11ea-935e-3afefb881d88.png)

version 1.8.5:

![Screen Shot 2020-06-26 at 11 55 36 AM](https://user-images.githubusercontent.com/46511495/85821974-fa976700-b7a3-11ea-89b2-b7574f6257fb.png)

Sorry if it's hard to see but there are background color around each line of field

How do i remove these ?

**Comment by abidibo** [comment]
Hi @linhnvhicts ,
the new baton versions come with this bg to increase readability. You can disable it by overriding a simple css rule:

```
<style>
.change-form #content-main>form .form-row, .passwordchange #content-main>form .form-row {
    background: #fff !important;
}
</style>
```

**Comment by AliPolat** [comment]
Thank you. Sometimes it is nice to disable this feature. But how about the spacing between fields. It remains the same. Is it possible to decrease this padding by the same css rule overriding ?
