### ISSUE TITLE
refresh layout on window resize

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#77]
Hi,
I noticed that whenever I resize the browser window, the overall layout is broken, until I manually reload.
This clearly manifests when one extends the window size horizontally beyond the footer: the new space is just a white block.
Is there a good way to fix this?
Thanks!

**Comment by abidibo** [comment]
It's the menu that autosizes at page load, now I've added autoresizing on window resize, and I'll keep this fix unless it will reduce performance, install baton 1.9.2

**Comment by etanter** [comment]
works perfectly, thanks!!
