### ISSUE TITLE
Menu in Login Page

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#8]
Hi 

Application menu bar appears often in the login page.  I can only get rid of it by clearing everything in the browser cache several times.    

![login](https://user-images.githubusercontent.com/1778756/39577436-059dfa62-4eea-11e8-9b55-6a1aa8851567.png)

Thank you very much fo your kind help.

**Comment by abidibo** [comment]
Hi,

I can't reproduce this bug.

- do you use a custom login template (it seems different from the baton default one)
- can you run `location.pathname` in your browser console in the login page and post here the output
- some other custom stuff in your project that may interfere?

**Comment by AliPolat** [comment]
- I use costumised admin index.html 
- location.pathname produces  "/login/"
- I use also django-admin-reorder

thank you..

**Comment by abidibo** [comment]
Can I see your custom index code? Also the login page seems different to me.

**Comment by AliPolat** [comment]
here is my index.html :

{% extends "admin/index.html" %}
{% load i18n static %}


{% block content %}
<div id="content-main">

{% if app_list %}
    {% for app in app_list %}
        <div class="app-{{ app.app_label }} module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">{{ app.name }}</a>
        </caption>
        {% for model in app.models %}
            <tr class="model-{{ model.object_name|lower }}">
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                {% if model.name == 'Satışlar' %}
                  <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Ekle Sat' %}</a></td>
                {% else %}
                  <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
                {% endif %}
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                {% if model.name == 'Satışlar' %}
                  <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Stoktan Sat' %}</a></td>
                {% else %}
                  <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
                {% endif %}
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans "You don't have permission to edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

**Comment by abidibo** [comment]
Ok, not useful.

So you don't have a custom login page, nor a custom admin base_site template?

This is how should look the default login page: no navbar, no menu, a centered bordered box containing the input fields

![screenshot from 2018-05-03 15-40-07](https://user-images.githubusercontent.com/444093/39580040-741bdfc4-4ee8-11e8-9ce9-d9529f8ecca9.png)

Also, in your browser console, when you have the menu sidebar in the login page, run this stuff:
`window.Baton.page()` and post here the output please.

**Comment by abidibo** [comment]
Oh... wait I see.

Which is your login page url? Maybe you don't have the `admin` part?

**Comment by AliPolat** [comment]
Yes I dont have admin part.

**Comment by AliPolat** [comment]
minyon.azurewebsites.net

**Comment by abidibo** [comment]
Let's continue this conversation on skype, you may find me as abidibo
