### ISSUE TITLE
base url not considered for (some) admin statics

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#81]
Hi,

baton seems to keep trying to get some static media (in that particular case, `admin/img/sorting-icons.svg`) by referring to the domain root (eg. `https://mywebsite.com/static/...`), instead of considering the `BASE_URL` parameter from the admin `settings.py` file.
or is there some baton specific parameter to set?

thanks!

**Comment by abidibo** [comment]
Should be fixed in develop, I need to compile also django images in the bundle to address this

**Comment by etanter** [comment]
ok, thanks! looking forward to next release ;-)

**Comment by abidibo** [comment]
well, this will fix all django images included in css that won't have anymore a `/static/` prefix. But baton's svg and fonts will still be served from `static`, that because I need to know the proper URL before compiling the bundle, if this is a problem for you, you can edit the `webpack.config.babel.js` file and recompile the app:

```js
  // File loaders
  webpackConfig.module.rules.push(
    {
      test: /\.(eot|woff|woff2|ttf|png|jpe?g|gif)(\?\S*)?$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: env.NODE_ENV === 'development' ? 5e6 : 1e4,
          publicPath: '/static/baton/app/dist/',
        }
      }
    },
    {
      test: /\.svg$/i,
      use: [
        {
          loader: 'url-loader',
          options: {
            limit: env.NODE_ENV === 'development' ? 5e6 : 1e4,
            publicPath: '/static/baton/app/dist/',
            generator: (content) => svgToMiniDataURI(content.toString()),
          },
        },
      ],
    },
  )
```

**Comment by etanter** [comment]
I see, thanks for the info. Not sure if this recompilation is viable for my purposes, but I'll look into it.
