### ISSUE TITLE
Date hierarchy field name display

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#83]
Is it possible to display date hierarchy field name beside date values so that user can get meaning of hierarchy.. 
Thank you..

**Comment by abidibo** [comment]
Hi @AliPolat m
unfortunately this isn't possible without overriding django stuff, and I don't want to. But you can do it, take a look at:
- `contrib/admin/templatetags/admin_list.py` `date_hierarchy` function
- `contrib/admin/templates/admin/date_hierarchy.html`
