### ISSUE TITLE
is it possible to revert the user menu, or compress it a lot?

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#86]
Hi,
For a menu-intensive app, the new design of the user menu (with icon, change passwd, logout) is way too space consuming and too "visually intense". Is there a template to customize to design a more minimal version (more akin to the prior, discrete design)? 
Otherwise, I can just hide it with `display: none` in CSS and find a way to put the link to logout/change pwd in some other place, of course, but if there's a more "civilized" way to customize it, I'd rather use it.
Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,

we decided to follow this new layout design which is great for our kind of applications. I'll see if I can add some options for moving the links in the footer. Supporting both layouts (user menu in the topbar or in the sidebar) can add too complexity, I'll think about it.

**Comment by etanter** [comment]
Hi @abidibo, thanks for the consideration, I hope this turns out to be feasible!

**Comment by etanter** [comment]
@abidibo do you have any update on this? thanks

**Comment by abidibo** [comment]
> @abidibo do you have any update on this? thanks

Hi @etanter , I'm quite busy at the moment and dealing just with bugs. But I'll look into it whenever possible

**Comment by etanter** [comment]
Thanks, for now I decided to rollback and stick to 1.9.3. I'll stay tuned!

**Comment by abidibo** [comment]
I ended up with implementing an expand/collapse functionality, possibly this is the best I can do, I hope it helps

![Screenshot from 2020-10-08 17-03-35](https://user-images.githubusercontent.com/444093/95477401-9716fb00-0988-11eb-8480-50f9dfa748f0.png)

![Screenshot from 2020-10-08 17-03-41](https://user-images.githubusercontent.com/444093/95477410-99795500-0988-11eb-845a-2f76c59eeeeb.png)
