### ISSUE TITLE
Tuning Horizontal and vertical spacing between fields.

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#87]
Some users request to get more information on the screen at first sight. 

Is it possible to tune spacing between fields in the admin change page without breaking the rules of django baton such as the below solution.

Thank You.   

Hi @linhnvhicts ,
the new baton versions come with this bg to increase readability. You can disable it by overriding a simple css rule:

```
<style>
.change-form #content-main>form .form-row, .passwordchange #content-main>form .form-row {
    background: #fff !important;
}
</style>
```

_Originally posted by @abidibo in https://github.com/otto-torino/django-baton/issues/76#issuecomment-650002148_

**Comment by abidibo** [comment]
Hi @AliPolat ,

can you try something like:

```
.change-form #content-main>form .form-row, .passwordchange #content-main>form .form-row {
    padding: .2rem .5rem !important;
}
```

**Comment by AliPolat** [comment]
Thank you..
