### ISSUE TITLE
Input fields wrap seperately from labels

### ISSUE THREAD

**Issue by avere001** [otto-torino/django-baton#94]
At this screen width, both the state and cell phone field labels are not next to their inputs:
![image](https://user-images.githubusercontent.com/5581459/92648891-07a1fd80-f29f-11ea-944b-4d7e046aa92a.png)

Here is another example of the weird wrapping:
![image](https://user-images.githubusercontent.com/5581459/92648775-d1647e00-f29e-11ea-8770-185411a0c5e5.png)

This is the relevant part of fieldsets, but this happens with all of the model add/change pages.
```python
fieldsets = (('Owner', {
    'fields': (
        ("first_name", "last_name",),
        ("address", "city", "state", "postal_code",),
        ("home_phone", "work_phone", "cell_phone",),
        ("email",)),
    'classes': ('baton-tabs-init', ...)
}), ...)
```

**Comment by abidibo** [comment]
Yeah, this is a problem with fields in the same line, two fields are supported, more fields can lead to weird behaviour. Fields in the same line is something we use rarely. I'll look into it.

**Comment by avere001** [comment]
Okay thank you. In the meantime, is there any way to reduce the spacing between two rows to make it look like the address fields are still in a group?

**Comment by abidibo** [comment]
I would use Baton grouped tabs feature: you can create a tab with two or more fieldsets, just place all the "address like" fields in the same fieldset

**Comment by abidibo** [comment]
Also I'll really look into it, but I'm not sure I'll fix this, I'm seeing that also the default django admin is somewhat bad looking with many fields in the same line, it's not easy to be responsive in an efficient way, we'll see...

**Comment by avere001** [comment]
Thank you for your help. It took me awhile to figure out the tab fieldset groups, but that works perfect for me.

I did notice however that this sometime happens with only the two columns, but it is much harder to get the specific screen widths at which this happens.
